/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Inuciian (https://sketchfab.com/Inuciian)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/479b5f3c493349b18c59dbcbe354d98f
title: Baba Yaga's hut
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function ModelHut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)

  
  return (
    <group ref={group} {...props} dispose={null} scale={500} position={[6000,-10000,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-2.19, -6, 3.41]} rotation={[0, 0, -0.1]}>
          <mesh geometry={nodes.lady_0.geometry} material={materials.lady_mat} />
        </group>
        <group position={[-2.19, -6, 3.41]} rotation={[0, 0, -0.13]} scale={1.37}>
          <mesh geometry={nodes.cage_0.geometry} material={nodes.cage_0.material} />
        </group>
        <group position={[3.28, 4.27, 4.59]} rotation={[0.41, 0.31, 1.8]}>
          <mesh
            name="bat_0"
            geometry={nodes.bat_0.geometry}
            material={materials.bat_mat}
            morphTargetDictionary={nodes.bat_0.morphTargetDictionary}
            morphTargetInfluences={nodes.bat_0.morphTargetInfluences}
          />
        </group>
        <group position={[-11.98, -0.07, -0.16]} rotation={[0.11, 0.11, -0.69]} scale={1.01}>
          <group position={[0.14, -0.6, 0.41]} rotation={[-0.14, 0.32, -2.84]} scale={0.99}>
            <mesh geometry={nodes.oar001_0.geometry} material={nodes.oar001_0.material} />
          </group>
          <group position={[-0.29, -0.66, 0.46]} rotation={[-0.2, -0.44, -0.43]} scale={0.99}>
            <mesh geometry={nodes.oar_0.geometry} material={nodes.oar_0.material} />
          </group>
          <group position={[0.34, -0.85, 1.08]} rotation={[-0.01, -0.15, -0.86]} scale={0.99}>
            <mesh geometry={nodes.cross_0.geometry} material={nodes.cross_0.material} />
          </group>
          <group position={[0.24, 1.02, 0.86]} rotation={[2.57, -0.56, 2.16]} scale={0.99}>
            <mesh geometry={nodes.sword_0.geometry} material={materials.sword_mat} />
          </group>
          <group position={[-0.1, 0.94, 0.04]} rotation={[-0.01, -0.15, 0.15]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.knight_0.geometry} material={materials.knight_mat} />
          </group>
          <group position={[0, -0.48, -0.42]} rotation={[-0.12, -0.13, 2.97]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.peasent_0.geometry} material={materials.peasant_mat} />
          </group>
          <group position={[-0.07, -1.15, -0.19]} rotation={[-0.03, 0.06, -0.03]} scale={[0.99, 0.99, 0.99]}>
            <mesh geometry={nodes.monk_0.geometry} material={materials.monk_material} />
          </group>
          <mesh geometry={nodes.boat_0.geometry} material={materials.boat_mat} />
        </group>
        <group position={[-1.69, 0.57, -0.08]} rotation={[-0.65, -0.79, -1.1]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder034_0.geometry} material={nodes.Cylinder034_0.material} />
        </group>
        <group position={[3.51, -2.8, 5.2]} scale={[0.12, 0.12, 0.19]}>
          <mesh
            name="fire001_0"
            geometry={nodes.fire001_0.geometry}
            material={nodes.fire001_0.material}
            morphTargetDictionary={nodes.fire001_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire001_0.morphTargetInfluences}
          />
        </group>
        <group position={[3.62, -2.74, 5.05]} scale={[0.12, 0.12, 0.19]}>
          <mesh
            name="fire002_0"
            geometry={nodes.fire002_0.geometry}
            material={nodes.fire002_0.material}
            morphTargetDictionary={nodes.fire002_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire002_0.morphTargetInfluences}
          />
        </group>
        <group position={[3.78, 3.24, 0.99]} scale={[0.12, 0.12, 0.19]}>
          <mesh
            name="fire003_0"
            geometry={nodes.fire003_0.geometry}
            material={nodes.fire003_0.material}
            morphTargetDictionary={nodes.fire003_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire003_0.morphTargetInfluences}
          />
        </group>
        <group position={[3.69, 3.37, 0.7]} scale={[0.12, 0.12, 0.19]}>
          <mesh
            name="fire004_0"
            geometry={nodes.fire004_0.geometry}
            material={nodes.fire004_0.material}
            morphTargetDictionary={nodes.fire004_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire004_0.morphTargetInfluences}
          />
        </group>
        <group position={[-3.07, -2.39, 1]} scale={[0.12, 0.12, 0.19]}>
          <mesh
            name="fire005_0"
            geometry={nodes.fire005_0.geometry}
            material={nodes.fire005_0.material}
            morphTargetDictionary={nodes.fire005_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire005_0.morphTargetInfluences}
          />
        </group>
        <group position={[-3.55, -6.23, 1.36]} rotation={[0.15, 0.2, -0.06]} scale={[0.49, 0.49, 0.82]}>
          <mesh
            name="fire006_0"
            geometry={nodes.fire006_0.geometry}
            material={nodes.fire006_0.material}
            morphTargetDictionary={nodes.fire006_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire006_0.morphTargetInfluences}
          />
        </group>
        <group position={[2.71, 4.62, 0.17]} rotation={[-0.07, -0.01, 2.82]}>
          <mesh
            name="rat001_0"
            geometry={nodes.rat001_0.geometry}
            material={nodes.rat001_0.material}
            morphTargetDictionary={nodes.rat001_0.morphTargetDictionary}
            morphTargetInfluences={nodes.rat001_0.morphTargetInfluences}
          />
        </group>
        <group position={[-6.16, -3.25, 2.65]} rotation={[1.01, 0.39, 2.36]}>
          <group position={[-0.07, -0.01, 0.13]} rotation={[0.42, 0.76, 1.07]}>
            <mesh geometry={nodes.Imp_0.geometry} material={nodes.Imp_0.material} />
          </group>
          <mesh geometry={nodes.broom002_0.geometry} material={nodes.broom002_0.material} />
        </group>
        <group position={[-1.56, 0.68, 0.07]} rotation={[-0.02, 0, 0]} scale={[1, 1, 1]}>
          <mesh
            name="cauldron_0"
            geometry={nodes.cauldron_0.geometry}
            material={materials['cauldron_mat.001']}
            morphTargetDictionary={nodes.cauldron_0.morphTargetDictionary}
            morphTargetInfluences={nodes.cauldron_0.morphTargetInfluences}
          />
        </group>
        <group position={[3.4, -2.03, 5.47]} rotation={[0, 0, -0.01]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.hut_walls_0.geometry} material={materials.hut_walls_mat} />
        </group>
        <group position={[3.4, -2.03, 5.16]} rotation={[0, 0, -0.01]} scale={[1.95, 1.95, 2.16]}>
          <mesh geometry={nodes.hut_roof_0.geometry} material={nodes.hut_roof_0.material} />
        </group>
        <group position={[1.55, -2.07, 5.04]} rotation={[0, -0.09, -0.01]} scale={[0.11, 0.51, 0.65]}>
          <mesh geometry={nodes.Cube002_0.geometry} material={nodes.Cube002_0.material} />
        </group>
        <group position={[1.48, -1.99, 5.68]} rotation={[0, -0.09, -0.01]} scale={[0.11, 0.51, 0.65]}>
          <mesh geometry={nodes.Cube003_0.geometry} material={nodes.Cube003_0.material} />
        </group>
        <group position={[1.6, -1.99, 4.38]} rotation={[0, -0.09, -0.01]} scale={[0.11, 0.51, 0.65]}>
          <mesh geometry={nodes.Cube004_0.geometry} material={nodes.Cube004_0.material} />
        </group>
        <group position={[1.54, -2.58, 5.03]} rotation={[0, -0.09, -1.02]} scale={[0.32, 0.32, 0.32]}>
          <mesh geometry={nodes.Cube005_0.geometry} material={nodes.Cube005_0.material} />
        </group>
        <group position={[1.54, -1.6, 5.03]} rotation={[0, -0.09, -2.35]} scale={[-0.32, 0.32, 0.32]}>
          <mesh geometry={nodes.Cube006_0.geometry} material={nodes.Cube006_0.material} />
        </group>
        <group position={[3.21, -0.9, 3.61]} rotation={[1.55, -0.22, 1.57]} scale={[0.16, 1.34, 0.89]}>
          <mesh geometry={nodes.Cube007_0.geometry} material={nodes.Cube007_0.material} />
        </group>
        <group position={[3.19, -3.31, 3.61]} rotation={[1.55, 0.1, 1.57]} scale={[0.16, 1.34, 0.89]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={nodes.Cube009_0.material} />
        </group>
        <group position={[2.58, -1.79, 3.64]} rotation={[-0.66, -1.54, -0.66]} scale={[0.12, 1.38, 0.91]}>
          <mesh geometry={nodes.Cube010_0.geometry} material={nodes.Cube010_0.material} />
        </group>
        <group position={[4.28, -2.28, 3.66]} rotation={[0.75, 1.55, 2.39]} scale={[0.11, 1.39, 0.89]}>
          <mesh geometry={nodes.Cube011_0.geometry} material={nodes.Cube011_0.material} />
        </group>
        <group position={[3.36, -0.25, 7.65]} rotation={[0, 0, -0.01]} scale={[0.49, 0.49, 0.49]}>
          <mesh geometry={nodes.hut_walls_small_0.geometry} material={nodes.hut_walls_small_0.material} />
        </group>
        <group position={[3.37, -0.89, 8.38]} rotation={[0.46, 0, 0]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.hut_roof_2_0.geometry} material={nodes.hut_roof_2_0.material} />
        </group>
        <group position={[3.41, -0.36, 5.7]} rotation={[0, 0, -0.01]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.Cube016_0.geometry} material={nodes.Cube016_0.material} />
        </group>
        <group position={[4.31, -3.35, 6.04]} rotation={[0, 0, -0.01]} scale={[1.99, 1.99, 1.99]}>
          <mesh geometry={nodes.chimney_0.geometry} material={materials.chimney_mat} />
        </group>
        <group position={[3.42, -2.13, 1.75]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.hut_stand_0.geometry} material={materials.hut_stand} />
        </group>
        <group position={[4.01, -0.57, 4.67]} rotation={[-0.1, -0.02, 0.47]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.hut_door_0.geometry} material={nodes.hut_door_0.material} />
        </group>
        <group position={[5.28, -2.52, 4.96]} rotation={[0, 0.09, 0.79]} scale={[-0.32, 0.32, 0.32]}>
          <mesh geometry={nodes.Cube020_0.geometry} material={nodes.Cube020_0.material} />
        </group>
        <group position={[5.28, -1.55, 4.96]} rotation={[0, 0.09, 2.12]} scale={[0.32, 0.32, 0.32]}>
          <mesh geometry={nodes.Cube021_0.geometry} material={nodes.Cube021_0.material} />
        </group>
        <group position={[5.22, -2.13, 4.31]} rotation={[0, 0.09, 3.14]} scale={[0.11, 0.51, 0.65]}>
          <mesh geometry={nodes.Cube022_0.geometry} material={nodes.Cube022_0.material} />
        </group>
        <group position={[5.33, -2.13, 5.61]} rotation={[0, 0.09, 3.14]} scale={[0.11, 0.51, 0.65]}>
          <mesh geometry={nodes.Cube023_0.geometry} material={nodes.Cube023_0.material} />
        </group>
        <group position={[5.27, -2.05, 4.97]} rotation={[0, 0.09, 3.14]} scale={[0.11, 0.51, 0.65]}>
          <mesh geometry={nodes.Cube024_0.geometry} material={nodes.Cube024_0.material} />
        </group>
        <group position={[3.8, 1.29, 0.04]} rotation={[0.32, -0.04, -0.12]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.ladder_1_0.geometry} material={nodes.ladder_1_0.material} />
        </group>
        <group position={[3.17, -2, 3.76]} rotation={[0, 0, -0.01]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.hut_floor_0.geometry} material={materials.hut_floor_mat} />
        </group>
        <group position={[1.34, -0.22, 0.52]} rotation={[0.15, -0.33, 0.04]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.broom_0.geometry} material={nodes.broom_0.material} />
        </group>
        <group position={[1.09, -0.28, 0.05]} rotation={[-0.04, -0.02, 1.35]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.stump_0.geometry} material={nodes.stump_0.material} />
        </group>
        <group position={[-2.22, 5.44, -0.26]} rotation={[-0.78, -0.05, 0.16]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fishing_rod_0.geometry} material={nodes.fishing_rod_0.material} />
        </group>
        <group position={[-2.37, -7.27, 2.13]} rotation={[1.57, -0.13, 0]} scale={[0.09, 1.31, 0.51]}>
          <mesh geometry={nodes.Cube008_0.geometry} material={nodes.Cube008_0.material} />
        </group>
        <group position={[-2.23, -6, 3.49]} rotation={[0, 0, -0.13]} scale={[1.37, 1.24, 1.24]}>
          <mesh geometry={nodes.Cylinder026_0.geometry} material={nodes.Cylinder026_0.material} />
        </group>
        <group position={[-2.16, -3.34, 0.2]} rotation={[-0.17, -0.11, 0.14]} scale={[0.36, 0.36, 0.1]}>
          <mesh geometry={nodes.rocks_1_0.geometry} material={nodes.rocks_1_0.material} />
        </group>
        <group position={[-1.52, -5.41, 0.48]} rotation={[0.08, -0.01, 0.62]} scale={[0.34, 0.34, 0.05]}>
          <mesh geometry={nodes.rocks_1001_0.geometry} material={nodes.rocks_1001_0.material} />
        </group>
        <group position={[-2.6, 5.13, -0.22]} rotation={[-0.04, -0.03, 0]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.bucket_0.geometry} material={nodes.bucket_0.material} />
        </group>
        <group position={[-3.77, -6.57, -0.35]} rotation={[-0.17, 0.13, -0.11]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.torch_0.geometry} material={nodes.torch_0.material} />
        </group>
        <group position={[-3.49, -1.74, -0.04]} rotation={[-0.02, -0.01, 0.66]} scale={[1.49, 1.49, 1.49]}>
          <mesh geometry={nodes.bench_0.geometry} material={materials.bench_mat} />
        </group>
        <group position={[-3.05, -6.42, 0.51]} rotation={[0.07, 0, 0.01]} scale={[1, 1, 1]}>
          <mesh
            name="rat_0"
            geometry={nodes.rat_0.geometry}
            material={nodes.rat_0.material}
            morphTargetDictionary={nodes.rat_0.morphTargetDictionary}
            morphTargetInfluences={nodes.rat_0.morphTargetInfluences}
          />
        </group>
        <group position={[-4.77, 5.18, -2.03]} rotation={[0, 0, -1.5]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.ground_0.geometry} material={materials.terrain_mat} />
        </group>
        <group position={[-2.3, 1.93, -0.14]} rotation={[0.12, 0.28, 1.32]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.rock_2_0.geometry} material={nodes.rock_2_0.material} />
        </group>
        <group position={[-6.08, -5.8, 1.33]} rotation={[-0.11, -0.18, -1.89]} scale={[13.68, 13.68, 13.68]}>
          <mesh geometry={nodes.rock_1_0.geometry} material={nodes.rock_1_0.material} />
        </group>
        <group position={[3.8, 4.87, -0.03]} rotation={[0.29, 0.1, 0.49]} scale={[1.08, 1.08, 1.08]}>
          <mesh geometry={nodes.Cube077_0.geometry} material={materials.Root} />
        </group>
        <group position={[5.15, 0.36, 0.14]} rotation={[-0.15, -0.29, -1.94]} scale={[3.35, 3.35, 3.35]}>
          <mesh geometry={nodes.Cube083_0.geometry} material={nodes.Cube083_0.material} />
        </group>
        <group position={[4.66, 8.62, -0.06]} rotation={[-0.11, 0.02, 1.35]} scale={[1.63, 1.63, 1.06]}>
          <mesh geometry={nodes.bush_1_0.geometry} material={nodes.bush_1_0.material} />
        </group>
        <group position={[-0.44, -1.44, 0.05]} rotation={[-0.07, -0.03, -0.65]} scale={[1.16, 1.16, 1.16]}>
          <mesh geometry={nodes.Cube088_0.geometry} material={materials.stool_mat} />
        </group>
        <group position={[12.76, 10.1, 15.32]} rotation={[-0.87, 0.65, -2.08]} scale={[0.53, 0.53, 0.53]} />
        <group position={[-1.53, 0.63, 0.93]} scale={1.65} />
        <group position={[3.51, -2.79, 5.32]} scale={1.79} />
        <group position={[-6.69, 2.67, -0.64]} rotation={[0.02, 0.07, 0.1]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant_0.geometry} material={nodes.cattail_plant_0.material} />
        </group>
        <group position={[-3.84, 3.47, -0.15]} rotation={[-0.02, -0.03, 0.42]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.rocks_3_0.geometry} material={nodes.rocks_3_0.material} />
        </group>
        <group position={[3.83, 3.33, 0.24]} rotation={[-0.03, -0.13, -1.93]} scale={[0.45, 0.48, 0.16]}>
          <mesh geometry={nodes.rocks_2_0.geometry} material={nodes.rocks_2_0.material} />
        </group>
        <group position={[-3, -2.17, 0.37]} rotation={[-0.06, -0.08, 2.34]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.candle002_0.geometry} material={nodes.candle002_0.material} />
        </group>
        <group position={[1.32, 6.71, -0.16]} rotation={[0, 0, 0.34]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.grass_2_0.geometry} material={nodes.grass_2_0.material} />
        </group>
        <group position={[-3.29, 1.36, -0.13]} rotation={[-0.14, 0.19, 1.42]} scale={[1.16, 1.16, 0.95]}>
          <mesh geometry={nodes.grass_1_0.geometry} material={nodes.grass_1_0.material} />
        </group>
        <group position={[2.19, -2.16, 4.67]} rotation={[-0.28, 0.77, 1.94]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.book_1002_0.geometry} material={nodes.book_1002_0.material} />
        </group>
        <group position={[2.64, -3.17, 3.8]} rotation={[0, 0, 1.44]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.shelf_0.geometry} material={nodes.shelf_0.material} />
        </group>
        <group position={[2.29, -2.13, 4.37]} rotation={[0, 0, 0.28]} scale={[0.12, 0.12, 0.12]}>
          <mesh geometry={nodes.Cube241_0.geometry} material={nodes.Cube241_0.material} />
        </group>
        <group position={[2.88, -3.12, 5.1]}>
          <mesh geometry={nodes.jar_glass_0.geometry} material={nodes.jar_glass_0.material} />
        </group>
        <group position={[2.61, -3.09, 5.05]}>
          <mesh geometry={nodes.bottle_1_0.geometry} material={nodes.bottle_1_0.material} />
        </group>
        <group position={[2.36, -3, 5.07]} rotation={[0.01, 0.02, 0]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.hourglass_0.geometry} material={materials.hourglas_mat} />
        </group>
        <group position={[3.01, -2.78, 3.85]} rotation={[0.02, -0.04, -2.03]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.book_1_0.geometry} material={nodes.book_1_0.material} />
        </group>
        <group position={[4.23, -2.24, 3.83]} rotation={[0.21, 0.22, 0.97]} scale={[0.28, 0.28, 0.28]}>
          <mesh geometry={nodes.rock_3001_0.geometry} material={nodes.rock_3001_0.material} />
        </group>
        <group position={[4.2, -2, 3.84]} rotation={[0.06, 0.2, 1.52]} scale={[0.41, 0.41, 0.41]}>
          <mesh geometry={nodes.rock_3_0.geometry} material={nodes.rock_3_0.material} />
        </group>
        <group position={[3.34, -2.61, 3.84]} rotation={[-0.18, 0.09, 2.92]} scale={[0.29, 0.29, 0.29]}>
          <mesh geometry={nodes.rock_3002_0.geometry} material={nodes.rock_3002_0.material} />
        </group>
        <group position={[2.76, -2.68, 3.81]} rotation={[-0.15, 0.16, 2.93]} scale={[0.32, 0.32, 0.32]}>
          <mesh geometry={nodes.rock_3003_0.geometry} material={nodes.rock_3003_0.material} />
        </group>
        <group position={[2.74, -2.77, 3.8]} rotation={[-0.15, 0.16, 2.93]} scale={[0.2, 0.2, 0.2]}>
          <mesh geometry={nodes.rock_3004_0.geometry} material={nodes.rock_3004_0.material} />
        </group>
        <group position={[3.86, -2.74, 5.33]} rotation={[-0.01, 0, 0.41]} scale={[0.1, 0.1, 0.1]}>
          <mesh geometry={nodes.garlic_0.geometry} material={materials.garlic_mat} />
        </group>
        <group position={[-3.59, -1.86, 0.47]} rotation={[0.01, -0.08, 1.78]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.bottle_2_0.geometry} material={nodes.bottle_2_0.material} />
        </group>
        <group position={[0.99, 4.46, -0.22]} rotation={[0, 0, -0.03]} scale={[1.93, 1.93, 1.93]}>
          <mesh geometry={nodes.Cylinder108_0.geometry} material={materials.well_material} />
        </group>
        <group position={[0.98, 4.5, 1.25]} rotation={[-Math.PI / 2, 1.23, Math.PI / 2]} scale={[1.04, 1.04, 1.04]}>
          <mesh geometry={nodes.Cylinder109_0.geometry} material={materials.pulley_mat} />
        </group>
        <group position={[5.33, 15.2, 2.8]} rotation={[0, 0, -2.09]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.Plane_0.geometry} material={nodes.Plane_0.material} />
        </group>
        <group position={[-13, -7.9, 2.82]} rotation={[-0.06, -0.08, 0.6]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.Plane001_0.geometry} material={nodes.Plane001_0.material} />
        </group>
        <group position={[-17.95, 0.6, 4.16]} rotation={[0, 0, 0.26]} scale={[2.43, 2.43, 2.43]}>
          <mesh geometry={nodes.Plane002_0.geometry} material={nodes.Plane002_0.material} />
        </group>
        <group position={[-6.22, 13.72, 2.14]} rotation={[0, 0, -0.99]} scale={[1.6, 1.6, 1.6]}>
          <mesh geometry={nodes.Plane003_0.geometry} material={nodes.Plane003_0.material} />
        </group>
        <group position={[-11.31, -2.92, 1.05]} rotation={[-0.03, -0.01, -0.32]} scale={[1.6, 1.6, 1]}>
          <mesh geometry={nodes.fog_0.geometry} material={nodes.fog_0.material} />
        </group>
        <group position={[-8.17, 7.19, 1.18]} rotation={[0, 0, -0.93]} scale={[1.6, 1.6, 1.11]}>
          <mesh geometry={nodes.Plane005_0.geometry} material={nodes.Plane005_0.material} />
        </group>
        <group position={[-5.66, 19.32, 5.33]} rotation={[0, 0, -1.32]} scale={[2.48, 2.48, 2.48]}>
          <mesh geometry={nodes.Plane006_0.geometry} material={nodes.Plane006_0.material} />
        </group>
        <group position={[8.2, -1.99, 4.09]} rotation={[-0.09, 0.03, 3.03]} scale={[1.28, 1.28, 1.28]}>
          <mesh geometry={nodes.Plane007_0.geometry} material={nodes.Plane007_0.material} />
        </group>
        <group position={[-1.48, -11.91, 4.34]} rotation={[0, -0.06, 1.58]} scale={[1.15, 1.15, 1.15]}>
          <mesh geometry={nodes.Plane008_0.geometry} material={nodes.Plane008_0.material} />
        </group>
        <group position={[9.55, -11.73, 6.63]} rotation={[0.02, -0.1, 2.45]} scale={[2, 2, 2]}>
          <mesh geometry={nodes.Plane009_0.geometry} material={nodes.Plane009_0.material} />
        </group>
        <group position={[9.1, 6.13, 4.09]} rotation={[-0.17, -0.11, -2.7]} scale={[1.62, 1.62, 1.62]}>
          <mesh geometry={nodes.Plane010_0.geometry} material={nodes.Plane010_0.material} />
        </group>
        <group position={[-19.46, 11.38, 4.38]} rotation={[0, 0, -0.47]} scale={[1.83, 1.83, 1.83]}>
          <mesh geometry={nodes.Plane011_0.geometry} material={nodes.Plane011_0.material} />
        </group>
        <group position={[-6.58, 8.15, -0.56]} rotation={[0, 0, -1.61]} scale={[1, 1, 1]}>
          <mesh
            name="water_0"
            geometry={nodes.water_0.geometry}
            material={materials.water_mat}
            morphTargetDictionary={nodes.water_0.morphTargetDictionary}
            morphTargetInfluences={nodes.water_0.morphTargetInfluences}
          />
        </group>
        <group position={[14.31, 4.45, 5.42]} rotation={[-0.08, 0, -2.99]} scale={[1.67, 1.67, 1.67]}>
          <mesh geometry={nodes.Plane012_0.geometry} material={nodes.Plane012_0.material} />
        </group>
        <group position={[2.58, -4.56, 0.54]} rotation={[-1.54, 0.66, 1.56]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fence_1_0.geometry} material={nodes.fence_1_0.material} />
        </group>
        <group position={[6.05, -0.54, 0.29]} rotation={[-1.53, 0, 1.56]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fence_2_0.geometry} material={materials.fence_2_mat} />
        </group>
        <group position={[-3.25, -1.82, 0.41]} rotation={[0.85, -1.19, 0.21]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.mushroom_1_0.geometry} material={nodes.mushroom_1_0.material} />
        </group>
        <group position={[-3.24, -2.27, 0.44]} rotation={[1.78, -1.04, 0.64]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.mushroom_2_0.geometry} material={nodes.mushroom_2_0.material} />
        </group>
        <group position={[-1.55, 0.44, 0.59]} rotation={[0.3, -0.07, -1.47]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.soup_ladle_0.geometry} material={nodes.soup_ladle_0.material} />
        </group>
        <group position={[-3.88, 23.26, 16.12]} rotation={[0.14, -0.07, -1.59]} scale={[3.97, 3.03, 3.97]}>
          <mesh geometry={nodes.Plane013_0.geometry} material={nodes.Plane013_0.material} />
        </group>
        <group position={[8.45, -9.26, 17.88]} rotation={[0.01, -0.09, 2.47]} scale={[3.31, 3.31, 3.31]}>
          <mesh geometry={nodes.Plane014_0.geometry} material={nodes.Plane014_0.material} />
        </group>
        <group position={[-17.08, -10.45, 17.35]} rotation={[-0.15, -0.02, 0.81]} scale={[4.89, 4.39, 4.89]}>
          <mesh geometry={nodes.Plane015_0.geometry} material={nodes.Plane015_0.material} />
        </group>
        <group position={[-9.58, -9.1, 21.43]} rotation={[-0.51, 0.32, 1.07]} scale={[3.06, 3.06, 3.06]}>
          <mesh geometry={nodes.Plane016_0.geometry} material={nodes.Plane016_0.material} />
        </group>
        <group position={[3.37, 0.23, 7.68]} rotation={[-1.75, 0.01, 0.13]} scale={[1.92, 1.92, 1.92]}>
          <mesh geometry={nodes.hut_window_small_0.geometry} material={nodes.hut_window_small_0.material} />
        </group>
        <group position={[3.72, -6.45, 1.74]} rotation={[-0.04, 0.05, 1.44]} scale={[2.38, 2.38, 2.38]}>
          <mesh geometry={nodes.tree_3_0.geometry} material={nodes.tree_3_0.material} />
        </group>
        <group position={[10.22, -4.5, 2.13]} rotation={[0, 0, -1.51]} scale={[2.22, 2.22, 2.22]}>
          <mesh geometry={nodes.Tree_1_0.geometry} material={nodes.Tree_1_0.material} />
        </group>
        <group position={[-2.84, -9.2, -0.1]} rotation={[0, 0, -2.64]} scale={[1.65, 1.65, 1.65]}>
          <mesh geometry={nodes.Hillhock_0.geometry} material={nodes.Hillhock_0.material} />
        </group>
        <group position={[2.04, -10.98, 1.02]} rotation={[0.07, -0.16, -1.67]} scale={[2.08, 2.08, 2.08]}>
          <mesh geometry={nodes.Hillhock001_0.geometry} material={nodes.Hillhock001_0.material} />
        </group>
        <group position={[5.08, -5.77, -0.36]} rotation={[-0.31, 0.07, -1.27]} scale={[2.08, 2.08, 2.08]}>
          <mesh geometry={nodes.Hillhock002_0.geometry} material={nodes.Hillhock002_0.material} />
        </group>
        <group position={[7, -8.36, 2.04]} rotation={[-0.32, -0.03, -1.12]} scale={[1.79, 1.79, 1.79]}>
          <mesh geometry={nodes.Hillhock003_0.geometry} material={nodes.Hillhock003_0.material} />
        </group>
        <group position={[9.65, 3.01, 0.06]} rotation={[-0.14, -0.2, -0.11]} scale={[2.11, 2.11, 2.11]}>
          <mesh geometry={nodes.Hillhock004_0.geometry} material={nodes.Hillhock004_0.material} />
        </group>
        <group position={[5.29, 3.23, -0.44]} rotation={[-0.16, 0.03, 0.12]} scale={[1.48, 1.48, 1.48]}>
          <mesh geometry={nodes.Hillhock005_0.geometry} material={nodes.Hillhock005_0.material} />
        </group>
        <group position={[-2.8, -9.99, 0.96]} rotation={[-0.4, -0.11, 2.13]} scale={[2.32, 2.32, 2.32]}>
          <mesh geometry={nodes.Cylinder132_0.geometry} material={nodes.Cylinder132_0.material} />
        </group>
        <group position={[-7.86, -7.49, -0.03]} rotation={[-0.07, -0.22, 0.74]} scale={[2.28, 2.28, 1.76]}>
          <mesh geometry={nodes.tree_2001_0.geometry} material={nodes.tree_2001_0.material} />
        </group>
        <group position={[8.66, -8.28, 3.22]} rotation={[0.11, -0.03, -2.96]} scale={[2.3, 2.29, 1.67]}>
          <mesh geometry={nodes.tree_2002_0.geometry} material={nodes.tree_2002_0.material} />
        </group>
        <group position={[7.59, 0.15, 0.32]} rotation={[-0.11, 0.21, 0.59]} scale={[2.36, 2.38, 2.05]}>
          <mesh geometry={nodes.tree_3001_0.geometry} material={nodes.tree_3001_0.material} />
        </group>
        <group position={[8.57, 3.62, 1.54]} rotation={[-0.08, -0.06, 2.94]} scale={[1.87, 1.87, 1.87]}>
          <mesh geometry={nodes.Tree_1001_0.geometry} material={nodes.Tree_1001_0.material} />
        </group>
        <group position={[5.79, 11.39, 0.05]} rotation={[-0.12, 0, 1.17]} scale={[1.61, 1.61, 1.61]}>
          <mesh geometry={nodes.Tree_1002_0.geometry} material={nodes.Tree_1002_0.material} />
        </group>
        <group position={[-4.55, -4.39, -0.05]} rotation={[0.05, -0.04, 0.31]} scale={[1.65, 1.65, 1.32]}>
          <mesh geometry={nodes.bush_1001_0.geometry} material={nodes.bush_1001_0.material} />
        </group>
        <group position={[10.75, 8.42, 0.44]} rotation={[-0.04, -0.25, -3.06]} scale={[2.15, 2.43, 1.68]}>
          <mesh geometry={nodes.bush_1002_0.geometry} material={nodes.bush_1002_0.material} />
        </group>
        <group position={[7.61, 7.16, -0.2]} rotation={[-0.05, -0.21, -1.48]} scale={[1.28, 1.7, 1.25]}>
          <mesh geometry={nodes.tree_2004_0.geometry} material={nodes.tree_2004_0.material} />
        </group>
        <group position={[5.45, -0.07, 0.29]} rotation={[-0.01, -0.06, -0.68]} scale={[1.48, 1.48, 1.18]}>
          <mesh geometry={nodes.bush_1003_0.geometry} material={nodes.bush_1003_0.material} />
        </group>
        <group position={[-7.21, -10.89, 1.39]} rotation={[-0.21, -0.21, 0.09]} scale={[2.66, 2.67, 1.73]}>
          <mesh geometry={nodes.bush_1004_0.geometry} material={nodes.bush_1004_0.material} />
        </group>
        <group position={[-10.83, 19.78, 1.78]} rotation={[-0.1, 0.03, 2.07]} scale={[1.87, 1.87, 1.87]}>
          <mesh geometry={nodes.Tree_1004_0.geometry} material={nodes.Tree_1004_0.material} />
        </group>
        <group position={[-14.45, 12.46, 1.13]} rotation={[0.09, -0.07, 2.13]} scale={[1.87, 1.87, 1.87]}>
          <mesh geometry={nodes.Tree_1005_0.geometry} material={nodes.Tree_1005_0.material} />
        </group>
        <group position={[-17.32, 8.3, -1.21]} rotation={[-0.03, -0.04, 2.22]} scale={[2.69, 2.7, 2.13]}>
          <mesh geometry={nodes.Hillhock006_0.geometry} material={nodes.Hillhock006_0.material} />
        </group>
        <group position={[-13.06, 13.55, -1.36]} rotation={[0, -0.13, 1.67]} scale={[2.98, 3.01, 3.21]}>
          <mesh geometry={nodes.Hillhock007_0.geometry} material={nodes.Hillhock007_0.material} />
        </group>
        <group position={[-4.63, 20.37, -1.36]} rotation={[0.02, -0.07, 1.38]} scale={[2.98, 3.01, 3.21]}>
          <mesh geometry={nodes.Hillhock008_0.geometry} material={nodes.Hillhock008_0.material} />
        </group>
        <group position={[-20.12, 0.45, -1.48]} rotation={[0.07, -0.08, 2.53]} scale={[2.69, 2.7, 2.13]}>
          <mesh geometry={nodes.Hillhock010_0.geometry} material={nodes.Hillhock010_0.material} />
        </group>
        <group position={[-3.68, -13.98, 1.81]} rotation={[-0.18, -0.03, 0.09]} scale={[2.22, 2.22, 2.22]}>
          <mesh geometry={nodes.Tree_1003_0.geometry} material={nodes.Tree_1003_0.material} />
        </group>
        <group position={[-15.33, 17.98, 0.86]} rotation={[0.29, -0.13, -1.06]} scale={[5.23, 5.9, 4.09]}>
          <mesh geometry={nodes.bush_1005_0.geometry} material={nodes.bush_1005_0.material} />
        </group>
        <group position={[-10.03, 14.85, 2.26]} rotation={[0.42, 0.12, 1.3]} scale={[2.57, 2.57, 2.57]}>
          <mesh geometry={nodes.Cylinder003_0.geometry} material={nodes.Cylinder003_0.material} />
        </group>
        <group position={[-5.63, 19.25, 1.25]} rotation={[0.25, -0.17, -2.57]} scale={[1.83, 1.83, 1.49]}>
          <mesh geometry={nodes.Cylinder005_0.geometry} material={nodes.Cylinder005_0.material} />
        </group>
        <group position={[-19.15, 3.32, 1.09]} rotation={[0.18, -0.02, 2.6]} scale={[3.77, 3.77, 3.02]}>
          <mesh geometry={nodes.bush_1006_0.geometry} material={nodes.bush_1006_0.material} />
        </group>
        <group position={[-0.31, 22.22, 1.65]} rotation={[0.23, 0.13, 1.85]} scale={[3.45, 3.45, 2.76]}>
          <mesh geometry={nodes.bush_1007_0.geometry} material={nodes.bush_1007_0.material} />
        </group>
        <group position={[-18.81, 10.94, -0.6]} rotation={[-0.07, -0.12, 2.22]} scale={[3.62, 4.05, 3.78]}>
          <mesh geometry={nodes.bush_1009_0.geometry} material={nodes.bush_1009_0.material} />
        </group>
        <group position={[-23.04, 5.2, 0.03]} rotation={[0.11, 0.07, -2.6]} scale={[3.52, 3.93, 3.68]}>
          <mesh geometry={nodes.bush_1010_0.geometry} material={nodes.bush_1010_0.material} />
        </group>
        <group position={[6.76, -3.7, 0.13]} rotation={[-0.28, -0.03, -2.65]} scale={[1.96, 1.98, 1.83]}>
          <mesh geometry={nodes.bush_1011_0.geometry} material={nodes.bush_1011_0.material} />
        </group>
        <group position={[2.75, -0.03, 5.97]} rotation={[-0.93, 1.29, 0.93]} scale={[1.65, 1.78, 1.65]}>
          <mesh geometry={nodes.Cylinder008_0.geometry} material={nodes.Cylinder008_0.material} />
        </group>
        <group position={[3.38, 0.03, 6.42]} rotation={[0.09, 0.16, -0.05]} scale={[2.25, 2.19, 2.25]}>
          <mesh geometry={nodes.Cylinder049_0.geometry} material={nodes.Cylinder049_0.material} />
        </group>
        <group position={[4.01, -0.06, 6.02]} rotation={[0.03, 0.14, -0.18]} scale={[2.04, 1.88, 2.04]}>
          <mesh geometry={nodes.Cylinder050_0.geometry} material={nodes.Cylinder050_0.material} />
        </group>
        <group position={[4.81, -0.22, 5.5]} rotation={[2.77, 0.57, -2.86]} scale={[2.04, 1.3, 2.04]}>
          <mesh geometry={nodes.Cylinder051_0.geometry} material={nodes.Cylinder051_0.material} />
        </group>
        <group position={[2.01, -0.25, 5.49]} rotation={[0.18, -0.79, 0.43]} scale={[1.65, 1.3, 1.65]}>
          <mesh geometry={nodes.Cylinder053_0.geometry} material={nodes.Cylinder053_0.material} />
        </group>
        <group position={[1.66, -3.46, 5.46]} rotation={[0.79, 0.13, 1.87]} scale={[1.65, 1.3, 1.65]}>
          <mesh geometry={nodes.Cylinder000_0.geometry} material={nodes.Cylinder000_0.material} />
        </group>
        <group position={[1.64, -0.56, 5.51]} rotation={[-2.54, 0.31, 1.64]} scale={[2.04, 1.3, 2.04]}>
          <mesh geometry={nodes.Cylinder001_0.geometry} material={nodes.Cylinder001_0.material} />
        </group>
        <group position={[1.48, -1.46, 6]} rotation={[-0.14, 0.03, 1.39]} scale={[2.04, 1.88, 2.04]}>
          <mesh geometry={nodes.Cylinder002_0.geometry} material={nodes.Cylinder002_0.material} />
        </group>
        <group position={[1.39, -2.1, 6.29]} rotation={[-0.16, 0.09, 1.54]} scale={[2.25, 2.19, 2.25]}>
          <mesh geometry={nodes.Cylinder004_0.geometry} material={nodes.Cylinder004_0.material} />
        </group>
        <group position={[1.52, -2.72, 5.89]} rotation={[-1.4, -0.22, 1.6]} scale={[1.65, 1.78, 1.65]}>
          <mesh geometry={nodes.Cylinder006_0.geometry} material={nodes.Cylinder006_0.material} />
        </group>
        <group position={[5.17, -1.32, 5.78]} rotation={[1.4, 0.22, -1.54]} scale={[1.65, 1.78, 1.65]}>
          <mesh geometry={nodes.Cylinder007_0.geometry} material={nodes.Cylinder007_0.material} />
        </group>
        <group position={[5.31, -1.94, 6.33]} rotation={[0.16, -0.09, -1.61]} scale={[2.25, 2.19, 2.25]}>
          <mesh geometry={nodes.Cylinder009_0.geometry} material={nodes.Cylinder009_0.material} />
        </group>
        <group position={[5.21, -2.57, 6.08]} rotation={[0.14, -0.03, -1.75]} scale={[2.04, 1.88, 2.04]}>
          <mesh geometry={nodes.Cylinder011_0.geometry} material={nodes.Cylinder011_0.material} />
        </group>
        <group position={[5.06, -3.47, 5.48]} rotation={[2.54, -0.31, -1.5]} scale={[2.04, 1.3, 2.04]}>
          <mesh geometry={nodes.Cylinder012_0.geometry} material={nodes.Cylinder012_0.material} />
        </group>
        <group position={[5.03, -0.58, 5.46]} rotation={[-0.79, -0.13, -1.27]} scale={[1.65, 1.3, 1.65]}>
          <mesh geometry={nodes.Cylinder013_0.geometry} material={nodes.Cylinder013_0.material} />
        </group>
        <group position={[3.35, -0.26, 8.05]} rotation={[0.2, -0.02, -0.01]} scale={[1.57, 1.38, 1.39]}>
          <mesh geometry={nodes.Cylinder014_0.geometry} material={nodes.Cylinder014_0.material} />
        </group>
        <group position={[4.78, -3.8, 5.49]} rotation={[-0.18, 0.79, -2.71]} scale={[1.65, 1.3, 1.65]}>
          <mesh geometry={nodes.Cylinder016_0.geometry} material={nodes.Cylinder016_0.material} />
        </group>
        <group position={[1.99, -3.82, 5.5]} rotation={[-2.77, -0.57, 0.28]} scale={[2.04, 1.3, 2.04]}>
          <mesh geometry={nodes.Cylinder018_0.geometry} material={nodes.Cylinder018_0.material} />
        </group>
        <group position={[2.79, -3.98, 6.02]} rotation={[-0.03, -0.14, 2.96]} scale={[2.04, 1.88, 2.04]}>
          <mesh geometry={nodes.Cylinder019_0.geometry} material={nodes.Cylinder019_0.material} />
        </group>
        <group position={[3.42, -4.07, 6.42]} rotation={[-0.09, -0.16, 3.09]} scale={[2.25, 2.19, 2.25]}>
          <mesh geometry={nodes.Cylinder020_0.geometry} material={nodes.Cylinder020_0.material} />
        </group>
        <group position={[4.04, -4.01, 5.97]} rotation={[0.93, -1.29, -2.21]} scale={[1.65, 1.78, 1.65]}>
          <mesh geometry={nodes.Cylinder021_0.geometry} material={nodes.Cylinder021_0.material} />
        </group>
        <group position={[3.73, -0.09, 7.77]} rotation={[0.26, 0.25, -0.36]} scale={[1.57, 1.15, 1.39]}>
          <mesh geometry={nodes.Cylinder022_0.geometry} material={nodes.Cylinder022_0.material} />
        </group>
        <group position={[2.97, -0.13, 7.76]} rotation={[0.15, -0.01, 0.29]} scale={[1.57, 1.19, 1.39]}>
          <mesh geometry={nodes.Cylinder023_0.geometry} material={nodes.Cylinder023_0.material} />
        </group>
        <group position={[1, -2.38, 7.32]} rotation={[0.01, 0.27, 1.86]} scale={[1.41, 1.07, 1.25]}>
          <mesh geometry={nodes.Cylinder025_0.geometry} material={nodes.Cylinder025_0.material} />
        </group>
        <group position={[0.97, -1.7, 7.34]} rotation={[-0.27, 0.37, 1.31]} scale={[1.41, 1.04, 1.25]}>
          <mesh geometry={nodes.Cylinder027_0.geometry} material={nodes.Cylinder027_0.material} />
        </group>
        <group position={[1.15, -2.04, 7.57]} rotation={[0.02, 0.32, 1.55]} scale={[1.41, 1.24, 1.25]}>
          <mesh geometry={nodes.Cylinder032_0.geometry} material={nodes.Cylinder032_0.material} />
        </group>
        <group position={[0.67, -2.02, 7.29]} rotation={[-3.05, -1.51, -1.34]} scale={[1.72, 1.72, 1.72]}>
          <mesh geometry={nodes.hut_window_small001_0.geometry} material={nodes.hut_window_small001_0.material} />
        </group>
        <group position={[1.75, -2.02, 7.79]} rotation={[0, 0.57, 1.56]} scale={[1.48, 1.48, 1.48]}>
          <mesh geometry={nodes.hut_roof_2001_0.geometry} material={nodes.hut_roof_2001_0.material} />
        </group>
        <group position={[1.1, -2.03, 7.21]} rotation={[0, 0.12, 1.57]} scale={[0.44, 0.44, 0.44]}>
          <mesh geometry={nodes.hut_walls_small001_0.geometry} material={nodes.hut_walls_small001_0.material} />
        </group>
        <group position={[3.35, -2.03, 5.83]} scale={1.43}>
          <mesh geometry={nodes.Plane017_0.geometry} material={nodes.Plane017_0.material} />
        </group>
        <group position={[-1.43, 0.56, -0.07]} rotation={[0.98, -0.39, 1.14]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder010_0.geometry} material={nodes.Cylinder010_0.material} />
        </group>
        <group position={[-1.46, 0.68, -0.03]} rotation={[1, 0.44, 1.67]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder030_0.geometry} material={nodes.Cylinder030_0.material} />
        </group>
        <group position={[-1.58, 0.78, -0.09]} rotation={[-0.89, 0.69, -2.35]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder031_0.geometry} material={nodes.Cylinder031_0.material} />
        </group>
        <group position={[-1.66, 0.76, -0.09]} rotation={[-1.02, 0.05, -1.87]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder033_0.geometry} material={nodes.Cylinder033_0.material} />
        </group>
        <group position={[-1.56, 0.55, -0.11]} rotation={[0.34, -1.04, 0.12]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder037_0.geometry} material={nodes.Cylinder037_0.material} />
        </group>
        <group position={[-5.97, -3.71, 0.53]} rotation={[0.12, -0.08, 0.34]} scale={[9.22, 9.22, 9.22]}>
          <mesh geometry={nodes.rock_1001_0.geometry} material={nodes.rock_1001_0.material} />
        </group>
        <group position={[-6.5, -1.85, 0.04]} rotation={[0, -0.31, -1.99]} scale={[5.72, 6.74, 4.79]}>
          <mesh geometry={nodes.rock_1002_0.geometry} material={nodes.rock_1002_0.material} />
        </group>
        <group position={[-8.44, -4.6, 0.49]} rotation={[-0.11, -0.27, -3.03]} scale={[8.98, 8.98, 8.98]}>
          <mesh geometry={nodes.rock_1003_0.geometry} material={nodes.rock_1003_0.material} />
        </group>
        <group position={[-5.36, 3.77, 0.15]} rotation={[0.11, -0.02, 0.23]} scale={[6.92, 6.92, 6.92]}>
          <mesh geometry={nodes.rock_1004_0.geometry} material={nodes.rock_1004_0.material} />
        </group>
        <group position={[-6.04, 4.9, -0.13]} rotation={[0.24, -0.09, 1.29]} scale={[4.82, 4.82, 4.82]}>
          <mesh geometry={nodes.rock_1005_0.geometry} material={nodes.rock_1005_0.material} />
        </group>
        <group position={[-7.01, 9.64, 0.28]} rotation={[0, 0.07, 2.73]} scale={[8.63, 9.65, 13.38]}>
          <mesh geometry={nodes.rock_1006_0.geometry} material={nodes.rock_1006_0.material} />
        </group>
        <group position={[-9.55, 4.35, 0.37]} rotation={[-0.05, 0.05, -1.28]} scale={[6.39, 7.55, 13.38]}>
          <mesh geometry={nodes.rock_1007_0.geometry} material={nodes.rock_1007_0.material} />
        </group>
        <group position={[-10.84, 3.01, -1.54]} rotation={[2.87, -1.04, 1.66]} scale={[6.22, 6.46, 12.79]}>
          <mesh geometry={nodes.rock_1008_0.geometry} material={nodes.rock_1008_0.material} />
        </group>
        <group position={[4.19, 5.44, 1.45]} rotation={[-0.15, -0.39, -1.7]} scale={[12.7, 12.7, 12.7]}>
          <mesh geometry={nodes.rock_1009_0.geometry} material={nodes.rock_1009_0.material} />
        </group>
        <group position={[2.58, 5, -0.04]} rotation={[0.17, -0.01, 0.85]} scale={[1.5, 1.5, 1.15]}>
          <mesh geometry={nodes.grass_1001_0.geometry} material={nodes.grass_1001_0.material} />
        </group>
        <group position={[1.67, 7.14, -0.19]} rotation={[-0.06, 0.03, 0.85]} scale={[1.5, 1.5, 1.15]}>
          <mesh geometry={nodes.grass_1002_0.geometry} material={nodes.grass_1002_0.material} />
        </group>
        <group position={[2.55, 7.75, -0.16]} rotation={[0.03, -0.11, -1.02]} scale={[2.03, 2.03, 1.55]}>
          <mesh geometry={nodes.grass_1003_0.geometry} material={nodes.grass_1003_0.material} />
        </group>
        <group position={[-0.65, 7.42, -0.46]} rotation={[-0.08, -0.1, 1]} scale={[1, 1, 1.26]}>
          <mesh geometry={nodes.grass_2001_0.geometry} material={nodes.grass_2001_0.material} />
        </group>
        <group position={[-0.63, 2.69, -0.09]} rotation={[0, 0, 0.1]} scale={[1, 1, 0.87]}>
          <mesh geometry={nodes.grass_2002_0.geometry} material={nodes.grass_2002_0.material} />
        </group>
        <group position={[1.44, 2.71, -0.02]} rotation={[0.27, -0.29, -0.37]} scale={[1.32, 1.32, 1.32]}>
          <mesh geometry={nodes.rock_2001_0.geometry} material={nodes.rock_2001_0.material} />
        </group>
        <group position={[3.13, 6.33, 0.86]} rotation={[-0.13, 0.11, 1.62]} scale={[9.33, 9.33, 9.33]}>
          <mesh geometry={nodes.rock_1010_0.geometry} material={nodes.rock_1010_0.material} />
        </group>
        <group position={[-0.39, 5.91, -0.21]} rotation={[-0.37, 0.11, 1.8]} scale={[2.12, 2.12, 2.12]}>
          <mesh geometry={nodes.rock_2002_0.geometry} material={nodes.rock_2002_0.material} />
        </group>
        <group position={[-0.09, -4.39, 0.43]} rotation={[-0.12, 0.03, -2.94]} scale={[1.2, 1.2, 1.2]}>
          <mesh geometry={nodes.stump001_0.geometry} material={nodes.stump001_0.material} />
        </group>
        <group position={[5.89, 2.62, 1.23]} rotation={[-0.18, -0.13, -0.7]} scale={[1.4, 1.4, 1.4]}>
          <mesh geometry={nodes.stump002_0.geometry} material={nodes.stump002_0.material} />
        </group>
        <group position={[4.87, 3.45, 0.92]} rotation={[-0.06, -0.2, 0.9]} scale={[1.97, 1.97, 1.51]}>
          <mesh geometry={nodes.grass_1004_0.geometry} material={nodes.grass_1004_0.material} />
        </group>
        <group position={[2.97, 2.49, 0.03]} rotation={[0.15, -0.06, 0.58]} scale={[1.5, 1.5, 1.15]}>
          <mesh geometry={nodes.grass_1005_0.geometry} material={nodes.grass_1005_0.material} />
        </group>
        <group position={[-0.56, 2.23, -0.03]} rotation={[0.17, 0.04, 1.08]} scale={[0.93, 0.93, 0.93]}>
          <mesh geometry={nodes.rock_2003_0.geometry} material={nodes.rock_2003_0.material} />
        </group>
        <group position={[-3.63, 1.28, -0.13]} rotation={[-0.01, 0.22, 1.05]} scale={[0.6, 0.6, 0.6]}>
          <mesh geometry={nodes.rock_2004_0.geometry} material={nodes.rock_2004_0.material} />
        </group>
        <group position={[-4.73, -1.75, -0.1]} rotation={[-0.14, 0.11, 1.04]} scale={[0.95, 0.95, 0.95]}>
          <mesh geometry={nodes.rock_2005_0.geometry} material={nodes.rock_2005_0.material} />
        </group>
        <group position={[1.97, -4.08, 0.4]} rotation={[-0.15, -0.09, -1.63]} scale={[2.51, 2.51, 2.51]}>
          <mesh geometry={nodes.rock_2006_0.geometry} material={nodes.rock_2006_0.material} />
        </group>
        <group position={[4.57, -3.6, 0.67]} rotation={[-0.18, -0.05, 2.13]} scale={[3.86, 3.86, 3.86]}>
          <mesh geometry={nodes.rock_2007_0.geometry} material={nodes.rock_2007_0.material} />
        </group>
        <group position={[9.48, -2.68, 2.99]} rotation={[-0.15, -0.11, 0.51]} scale={[16.55, 16.55, 16.55]}>
          <mesh geometry={nodes.rock_1011_0.geometry} material={nodes.rock_1011_0.material} />
        </group>
        <group position={[7.41, -6.1, 2.55]} rotation={[0.07, 0.54, 2.66]} scale={[12.96, 12.96, 12.96]}>
          <mesh geometry={nodes.rock_1012_0.geometry} material={nodes.rock_1012_0.material} />
        </group>
        <group position={[0.56, -0.06, 0.04]} rotation={[0.18, -0.06, 0.25]} scale={[1.28, 1.28, 1.05]}>
          <mesh geometry={nodes.grass_1006_0.geometry} material={nodes.grass_1006_0.material} />
        </group>
        <group position={[1.43, 8.91, 0.47]} rotation={[-0.03, 0.01, 0.04]} scale={[9.33, 9.33, 9.17]}>
          <mesh geometry={nodes.rock_1013_0.geometry} material={nodes.rock_1013_0.material} />
        </group>
        <group position={[-0.13, 9.35, -0.07]} rotation={[-0.51, -0.25, -2.76]} scale={[5.79, 7.05, 6.89]}>
          <mesh geometry={nodes.rock_1014_0.geometry} material={nodes.rock_1014_0.material} />
        </group>
        <group position={[-4.43, 4.4, -0.37]} rotation={[0.18, -0.22, -0.51]} scale={[2.37, 2.37, 2.37]}>
          <mesh geometry={nodes.rock_2008_0.geometry} material={nodes.rock_2008_0.material} />
        </group>
        <group position={[-3.84, 5.35, -0.32]} rotation={[-0.16, 0.11, -0.61]} scale={[1, 1, 1.3]}>
          <mesh geometry={nodes.grass_2003_0.geometry} material={nodes.grass_2003_0.material} />
        </group>
        <group position={[-4.69, 5.25, -0.38]} rotation={[0.02, -0.02, -0.83]} scale={[1, 1, 1.3]}>
          <mesh geometry={nodes.grass_2004_0.geometry} material={nodes.grass_2004_0.material} />
        </group>
        <group position={[-5.03, 5.89, -0.42]} rotation={[0.03, -0.11, -0.86]} scale={[1, 1, 1.3]}>
          <mesh geometry={nodes.grass_2005_0.geometry} material={nodes.grass_2005_0.material} />
        </group>
        <group position={[-6.25, 3.36, -0.49]} rotation={[0.05, -0.22, -0.89]} scale={[1, 1, 1.3]}>
          <mesh geometry={nodes.grass_2006_0.geometry} material={nodes.grass_2006_0.material} />
        </group>
        <group position={[-5.93, 2.83, -0.44]} rotation={[-0.11, -0.12, 0.01]} scale={[1.14, 1.14, 1.49]}>
          <mesh geometry={nodes.grass_2007_0.geometry} material={nodes.grass_2007_0.material} />
        </group>
        <group position={[-5.75, 2.04, -0.43]} rotation={[-0.11, -0.1, -1.12]} scale={[1.14, 1.14, 1.49]}>
          <mesh geometry={nodes.grass_2008_0.geometry} material={nodes.grass_2008_0.material} />
        </group>
        <group position={[-6.78, 1.41, -0.62]} rotation={[-0.04, -0.14, -0.53]} scale={[1.14, 1.14, 1.49]}>
          <mesh geometry={nodes.grass_2009_0.geometry} material={nodes.grass_2009_0.material} />
        </group>
        <group position={[-6.77, -0.84, -0.49]} rotation={[-0.14, -0.16, -1.74]} scale={[1.14, 1.14, 1.49]}>
          <mesh geometry={nodes.grass_2010_0.geometry} material={nodes.grass_2010_0.material} />
        </group>
        <group position={[-5.04, -2.3, -0.12]} rotation={[-0.11, 0.03, -2.21]} scale={[1.14, 1.14, 1.17]}>
          <mesh geometry={nodes.grass_2011_0.geometry} material={nodes.grass_2011_0.material} />
        </group>
        <group position={[-3.49, -6.27, 0.3]} rotation={[-0.09, 0.08, -1.88]} scale={[0.86, 0.87, 1.1]}>
          <mesh geometry={nodes.grass_2012_0.geometry} material={nodes.grass_2012_0.material} />
        </group>
        <group position={[-2.15, -7.14, 0.22]} rotation={[-0.05, 0.11, -2.29]} scale={[0.96, 0.97, 1.22]}>
          <mesh geometry={nodes.grass_2013_0.geometry} material={nodes.grass_2013_0.material} />
        </group>
        <group position={[-2.41, -8.76, 1.42]} rotation={[-0.06, 0.23, -1.47]} scale={[1.59, 1.61, 1.2]}>
          <mesh geometry={nodes.grass_2014_0.geometry} material={nodes.grass_2014_0.material} />
        </group>
        <group position={[-3.3, -8.88, 1.6]} rotation={[-0.34, -0.09, -2.38]} scale={[1.37, 1.39, 1.22]}>
          <mesh geometry={nodes.grass_2015_0.geometry} material={nodes.grass_2015_0.material} />
        </group>
        <group position={[3.06, -8.19, 2.71]} rotation={[-0.17, -0.02, -0.55]} scale={[1.93, 1.95, 1.45]}>
          <mesh geometry={nodes.grass_2016_0.geometry} material={nodes.grass_2016_0.material} />
        </group>
        <group position={[2.97, -5.74, 2.1]} rotation={[-0.35, 0.05, -2.38]} scale={[1.21, 1.23, 1.54]}>
          <mesh geometry={nodes.grass_2017_0.geometry} material={nodes.grass_2017_0.material} />
        </group>
        <group position={[0.72, -5.29, 0.51]} rotation={[-0.11, -0.08, -0.17]} scale={[1.21, 1.23, 1.52]}>
          <mesh geometry={nodes.grass_2018_0.geometry} material={nodes.grass_2018_0.material} />
        </group>
        <group position={[3.57, -4.16, 0.65]} rotation={[-0.13, -0.17, -1.15]} scale={[1.89, 1.89, 1.55]}>
          <mesh geometry={nodes.grass_1007_0.geometry} material={nodes.grass_1007_0.material} />
        </group>
        <group position={[2.94, -1.21, 0.25]} rotation={[-0.1, -0.11, -0.66]} scale={[1.57, 1.57, 1.29]}>
          <mesh geometry={nodes.grass_1008_0.geometry} material={nodes.grass_1008_0.material} />
        </group>
        <group position={[3.84, 1.4, 0.11]} rotation={[0, 0, 0.51]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.grass_2019_0.geometry} material={nodes.grass_2019_0.material} />
        </group>
        <group position={[1.87, 2.94, -0.04]} rotation={[0.07, -0.03, 0.3]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.grass_2020_0.geometry} material={nodes.grass_2020_0.material} />
        </group>
        <group position={[-4.41, 3.25, -0.28]} rotation={[-0.14, 0, -0.42]} scale={[0.9, 0.9, 0.8]}>
          <mesh geometry={nodes.grass_2021_0.geometry} material={nodes.grass_2021_0.material} />
        </group>
        <group position={[-3.06, 1.45, -0.16]} rotation={[-0.07, -0.04, 0.07]} scale={[0.9, 0.9, 0.8]}>
          <mesh geometry={nodes.grass_2022_0.geometry} material={nodes.grass_2022_0.material} />
        </group>
        <group position={[-3.52, -0.59, -0.1]} rotation={[0.04, 0.1, 1.94]} scale={[1.5, 1.5, 1.23]}>
          <mesh geometry={nodes.grass_1009_0.geometry} material={nodes.grass_1009_0.material} />
        </group>
        <group position={[-3.85, -1.3, 0.39]} rotation={[0, -0.01, -1.6]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.book_1001_0.geometry} material={nodes.book_1001_0.material} />
        </group>
        <group position={[-3.05, -2.39, 0.37]} rotation={[-0.01, -0.03, -2.9]} scale={[1.28, 1.28, 1.68]}>
          <mesh geometry={nodes.candle001_0.geometry} material={nodes.candle001_0.material} />
        </group>
        <group position={[-2.57, -2.49, -0.02]} rotation={[0, 0, -1.48]} scale={[1.2, 1.2, 1]}>
          <mesh geometry={nodes.candle003_0.geometry} material={nodes.candle003_0.material} />
        </group>
        <group position={[3.52, -2.8, 4.73]} rotation={[0.01, -0.02, -0.62]} scale={[1, 1, 1.29]}>
          <mesh geometry={nodes.candle004_0.geometry} material={nodes.candle004_0.material} />
        </group>
        <group position={[3.62, -2.73, 4.75]} rotation={[0.01, -0.02, -0.49]} scale={[1, 1, 0.83]}>
          <mesh geometry={nodes.candle_0.geometry} material={nodes.candle_0.material} />
        </group>
        <group position={[1.25, -5.61, 0.55]} rotation={[-1.6, 1.07, 1.61]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fence_1001_0.geometry} material={nodes.fence_1001_0.material} />
        </group>
        <group position={[5.37, -2.09, 0.5]} rotation={[-1.65, 0.59, 1.61]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fence_1002_0.geometry} material={nodes.fence_1002_0.material} />
        </group>
        <group position={[0.9, 6.19, -0.24]} rotation={[-1.56, -1.17, 1.71]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fence_1003_0.geometry} material={nodes.fence_1003_0.material} />
        </group>
        <group position={[2.55, -1.05, 3.83]} rotation={[0.36, -0.07, -0.2]} scale={[0.77, 0.77, 0.77]}>
          <mesh geometry={nodes.ladder_1001_0.geometry} material={nodes.ladder_1001_0.material} />
        </group>
        <group position={[3.73, 3.36, 0.36]} rotation={[-0.03, -0.09, -1.13]} scale={[1, 1, 0.91]}>
          <mesh geometry={nodes.candle005_0.geometry} material={nodes.candle005_0.material} />
        </group>
        <group position={[3.89, 3.38, 0.34]} rotation={[-0.02, -0.03, 2.82]} scale={[1.11, 1.11, 1.24]}>
          <mesh geometry={nodes.candle006_0.geometry} material={nodes.candle006_0.material} />
        </group>
        <group position={[3.84, 3.25, 0.34]} rotation={[0.01, -0.1, -2.88]} scale={[1.17, 1.17, 1.71]}>
          <mesh geometry={nodes.candle007_0.geometry} material={nodes.candle007_0.material} />
        </group>
        <group position={[0.97, 0.21, 0.05]} rotation={[-0.12, 0.08, -2.17]} scale={[1.34, 1.34, 1.46]}>
          <mesh geometry={nodes.mushroom_1001_0.geometry} material={nodes.mushroom_1001_0.material} />
        </group>
        <group position={[2.75, 2.73, 0.01]} rotation={[-0.16, 0.01, -2.18]} scale={[1.24, 1.24, 1.36]}>
          <mesh geometry={nodes.mushroom_1002_0.geometry} material={nodes.mushroom_1002_0.material} />
        </group>
        <group position={[2.45, 2.68, 0.05]} rotation={[0.17, -0.17, -0.62]} scale={[1.4, 1.4, 1.4]}>
          <mesh geometry={nodes.mushroom_2001_0.geometry} material={nodes.mushroom_2001_0.material} />
        </group>
        <group position={[2.34, -3.62, 0.38]} rotation={[-0.11, -0.06, -2.13]} scale={[2.26, 2.26, 2.46]}>
          <mesh geometry={nodes.mushroom_1003_0.geometry} material={nodes.mushroom_1003_0.material} />
        </group>
        <group position={[4.68, -1.89, 4.24]} rotation={[-0.28, 0.16, 0.44]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.broom001_0.geometry} material={nodes.broom001_0.material} />
        </group>
        <group position={[2.73, -3.14, 4.13]} rotation={[0.01, -1.12, -1.55]} scale={[0.76, 0.76, 0.76]}>
          <mesh geometry={nodes.book_1005_0.geometry} material={nodes.book_1005_0.material} />
        </group>
        <group position={[2.99, -3.12, 4.12]} rotation={[2.31, -1.55, 0.79]} scale={[0.66, 0.66, 0.66]}>
          <mesh geometry={nodes.book_1006_0.geometry} material={nodes.book_1006_0.material} />
        </group>
        <group position={[2.8, -3.18, 4.63]} rotation={[-0.03, 0.08, -3.05]} scale={[0.91, 0.91, 0.91]}>
          <mesh geometry={nodes.book_1008_0.geometry} material={nodes.book_1008_0.material} />
        </group>
        <group position={[2.8, -3.18, 4.73]} rotation={[-0.01, 0.08, 2.73]} scale={[0.92, 0.92, 0.92]}>
          <mesh geometry={nodes.book_1009_0.geometry} material={nodes.book_1009_0.material} />
        </group>
        <group position={[2.88, -3.12, 5.1]}>
          <mesh geometry={nodes.jar_0.geometry} material={nodes.jar_0.material} />
        </group>
        <group position={[2.49, -3.13, 4.6]}>
          <mesh geometry={nodes.jar001_0.geometry} material={nodes.jar001_0.material} />
        </group>
        <group position={[2.49, -3.13, 4.6]}>
          <mesh geometry={nodes.jar_glass001_0.geometry} material={nodes.jar_glass001_0.material} />
        </group>
        <group position={[-0.45, -6.81, 0.4]} rotation={[-0.13, -0.28, 0.5]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.rocks_3001_0.geometry} material={nodes.rocks_3001_0.material} />
        </group>
        <group position={[-3.18, -2, 0.52]} rotation={[0, 0, 0.29]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.jar002_0.geometry} material={nodes.jar002_0.material} />
        </group>
        <group position={[-3.18, -2, 0.52]} rotation={[0, 0, 0.29]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.jar_glass002_0.geometry} material={nodes.jar_glass002_0.material} />
        </group>
        <group position={[4.5, -1.16, 3.82]} rotation={[0, 0, -2.85]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.shelf001_0.geometry} material={nodes.shelf001_0.material} />
        </group>
        <group position={[4.44, -1.03, 4.55]} rotation={[0.01, -0.03, -1.4]} scale={[0.88, 0.88, 0.88]}>
          <mesh geometry={nodes.book_1011_0.geometry} material={nodes.book_1011_0.material} />
        </group>
        <group position={[4.34, -1.01, 5.11]} scale={0.87}>
          <mesh geometry={nodes.jar003_0.geometry} material={nodes.jar003_0.material} />
        </group>
        <group position={[4.34, -1.01, 5.11]} scale={0.87}>
          <mesh geometry={nodes.jar_glass003_0.geometry} material={nodes.jar_glass003_0.material} />
        </group>
        <group position={[4.48, -1.44, 5.1]} scale={[0.66, 0.66, 0.73]}>
          <mesh geometry={nodes.jar_glass004_0.geometry} material={nodes.jar_glass004_0.material} />
        </group>
        <group position={[4.48, -1.44, 5.1]} scale={[0.66, 0.66, 0.73]}>
          <mesh geometry={nodes.jar004_0.geometry} material={nodes.jar004_0.material} />
        </group>
        <group position={[3.89, -2.68, 4.84]} rotation={[-0.18, -0.05, 0.02]} scale={[1, 1, 0.62]}>
          <mesh geometry={nodes.bottle_1001_0.geometry} material={nodes.bottle_1001_0.material} />
        </group>
        <group position={[2.54, -3.04, 4.05]}>
          <mesh geometry={nodes.bottle_1002_0.geometry} material={nodes.bottle_1002_0.material} />
        </group>
        <group position={[2.35, -3.23, 4.05]}>
          <mesh geometry={nodes.bottle_1003_0.geometry} material={nodes.bottle_1003_0.material} />
        </group>
        <group position={[2.36, -3, 5.07]} rotation={[0.01, 0.02, 0]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.hourglass_glass_0.geometry} material={nodes.hourglass_glass_0.material} />
        </group>
        <group position={[2.23, -2.75, 3.91]} rotation={[0.03, 0.04, 0.65]} scale={[1.12, 1.12, 1.12]}>
          <mesh geometry={nodes.bottle_2001_0.geometry} material={nodes.bottle_2001_0.material} />
        </group>
        <group position={[-3.42, -1.56, 0.47]} rotation={[0, 0, 0.29]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.bottle_1004_0.geometry} material={nodes.bottle_1004_0.material} />
        </group>
        <group position={[4.11, -2.67, 4.85]} rotation={[-0.16, -0.01, 0.56]} scale={[1, 1, 0.62]}>
          <mesh geometry={nodes.bottle_1005_0.geometry} material={nodes.bottle_1005_0.material} />
        </group>
        <group position={[4.41, -0.83, 4.17]} rotation={[1.33, 0.24, 0.06]} scale={[0.81, 0.81, 0.81]}>
          <mesh geometry={nodes.book_1012_0.geometry} material={nodes.book_1012_0.material} />
        </group>
        <group position={[4.37, -1.09, 4.08]} rotation={[0.03, 0.04, 0.65]} scale={[1.12, 1.12, 1.12]}>
          <mesh geometry={nodes.bottle_2002_0.geometry} material={nodes.bottle_2002_0.material} />
        </group>
        <group position={[4.64, -1.26, 4.09]} rotation={[-0.02, 0.05, 0.67]} scale={[1.12, 1.12, 1.12]}>
          <mesh geometry={nodes.bottle_2003_0.geometry} material={nodes.bottle_2003_0.material} />
        </group>
        <group position={[4.48, -1.38, 4.08]}>
          <mesh geometry={nodes.bottle_1006_0.geometry} material={nodes.bottle_1006_0.material} />
        </group>
        <group position={[4.5, -1.41, 4.58]} scale={[1.66, 1.66, 1]}>
          <mesh geometry={nodes.bottle_1007_0.geometry} material={nodes.bottle_1007_0.material} />
        </group>
        <group position={[4.58, -1.98, 3.83]} rotation={[0.01, 0.01, 0.52]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.bucket001_0.geometry} material={nodes.bucket001_0.material} />
        </group>
        <group position={[2.77, 10.01, -0.06]} rotation={[-0.47, -0.22, -2.43]} scale={[1.95, 1.95, 1.56]}>
          <mesh geometry={nodes.bush_1012_0.geometry} material={nodes.bush_1012_0.material} />
        </group>
        <group position={[-2.36, 6.89, 1.13]} rotation={[0.02, 0.02, 0.4]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fishing_rod_hook_0.geometry} material={nodes.fishing_rod_hook_0.material} />
        </group>
        <group position={[-6.12, 2.65, -0.64]} rotation={[-0.03, 0.07, 0.88]} scale={[1.07, 1.07, 1.07]}>
          <mesh geometry={nodes.cattail_plant001_0.geometry} material={nodes.cattail_plant001_0.material} />
        </group>
        <group position={[-6, 2.42, -0.49]} rotation={[0.13, -0.05, 0.11]} scale={[0.86, 0.86, 0.86]}>
          <mesh geometry={nodes.cattail_plant002_0.geometry} material={nodes.cattail_plant002_0.material} />
        </group>
        <group position={[-6.4, 2.09, -0.59]} rotation={[-0.07, -0.16, 0.04]} scale={[0.92, 0.92, 0.92]}>
          <mesh geometry={nodes.cattail_plant003_0.geometry} material={nodes.cattail_plant003_0.material} />
        </group>
        <group position={[-6.09, 1.87, -0.59]} rotation={[0.14, -0.08, 0.73]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.cattail_plant004_0.geometry} material={nodes.cattail_plant004_0.material} />
        </group>
        <group position={[-6.35, 1.8, -0.58]} rotation={[0.1, -0.01, -2.21]} scale={[0.81, 0.81, 0.81]}>
          <mesh geometry={nodes.cattail_plant005_0.geometry} material={nodes.cattail_plant005_0.material} />
        </group>
        <group position={[-6.43, 1.39, -0.57]} rotation={[-0.03, 0.04, -0.24]} scale={[0.94, 0.94, 0.94]}>
          <mesh geometry={nodes.cattail_plant006_0.geometry} material={nodes.cattail_plant006_0.material} />
        </group>
        <group position={[-6.89, 1.73, -0.8]} rotation={[0.04, 0, -2.91]} scale={[1.02, 1.02, 1.02]}>
          <mesh geometry={nodes.cattail_plant007_0.geometry} material={nodes.cattail_plant007_0.material} />
        </group>
        <group position={[-6.79, 2.9, -0.69]} rotation={[-0.06, 0.04, 1.41]} scale={[0.95, 0.95, 0.95]}>
          <mesh geometry={nodes.cattail_plant008_0.geometry} material={nodes.cattail_plant008_0.material} />
        </group>
        <group position={[-6.98, 3.32, -0.69]} rotation={[0.01, -0.03, 2.41]} scale={[0.97, 0.97, 0.97]}>
          <mesh geometry={nodes.cattail_plant009_0.geometry} material={nodes.cattail_plant009_0.material} />
        </group>
        <group position={[-6.72, 3.5, -0.57]} rotation={[-0.01, -0.01, 0.03]} scale={[0.88, 0.88, 0.88]}>
          <mesh geometry={nodes.cattail_plant010_0.geometry} material={nodes.cattail_plant010_0.material} />
        </group>
        <group position={[-6.26, 3.73, -0.57]} rotation={[0, -0.01, 0.81]} scale={[0.8, 0.8, 0.8]}>
          <mesh geometry={nodes.cattail_plant011_0.geometry} material={nodes.cattail_plant011_0.material} />
        </group>
        <group position={[-6.61, 3.94, -0.73]} rotation={[-0.13, 0, 1.73]} scale={[0.8, 0.8, 0.8]}>
          <mesh geometry={nodes.cattail_plant012_0.geometry} material={nodes.cattail_plant012_0.material} />
        </group>
        <group position={[-7.01, 4.25, -0.73]} rotation={[-0.13, 0, 1.73]} scale={[0.94, 0.94, 0.94]}>
          <mesh geometry={nodes.cattail_plant013_0.geometry} material={nodes.cattail_plant013_0.material} />
        </group>
        <group position={[-6.4, 4.4, -0.73]} rotation={[0.1, 0.05, -0.35]} scale={[0.94, 0.94, 0.94]}>
          <mesh geometry={nodes.cattail_plant014_0.geometry} material={nodes.cattail_plant014_0.material} />
        </group>
        <group position={[-5.08, 5.1, -0.45]} rotation={[-0.02, 0.1, 0.37]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant015_0.geometry} material={nodes.cattail_plant015_0.material} />
        </group>
        <group position={[-4.36, 5.23, -0.39]} rotation={[0.07, 0, -1.35]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant016_0.geometry} material={nodes.cattail_plant016_0.material} />
        </group>
        <group position={[-4.36, 5.37, -0.37]} rotation={[-0.06, -0.01, 0.06]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant017_0.geometry} material={nodes.cattail_plant017_0.material} />
        </group>
        <group position={[-4.75, 5.52, -0.4]} rotation={[-0.06, -0.01, 0.06]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant018_0.geometry} material={nodes.cattail_plant018_0.material} />
        </group>
        <group position={[-4.84, 6.02, -0.45]} rotation={[0.03, -0.09, 1.85]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant019_0.geometry} material={nodes.cattail_plant019_0.material} />
        </group>
        <group position={[-4.74, 6.11, -0.48]} rotation={[-0.14, 0.05, 2.07]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant020_0.geometry} material={nodes.cattail_plant020_0.material} />
        </group>
        <group position={[-1.49, 0.79, -0.08]} rotation={[-0.1, 0.95, 2.99]} scale={[1.34, 1.06, 1.34]}>
          <mesh geometry={nodes.Cylinder029_0.geometry} material={nodes.Cylinder029_0.material} />
        </group>
        <group position={[-5.23, 6.32, -0.53]} rotation={[0.02, -0.17, 2.97]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant022_0.geometry} material={nodes.cattail_plant022_0.material} />
        </group>
        <group position={[-4.17, 6.28, -0.55]} rotation={[-0.07, 0.04, 1.44]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant023_0.geometry} material={nodes.cattail_plant023_0.material} />
        </group>
        <group position={[-4.01, 5.9, -0.47]} rotation={[0.09, 0, -1.54]} scale={[0.97, 0.97, 0.97]}>
          <mesh geometry={nodes.cattail_plant024_0.geometry} material={nodes.cattail_plant024_0.material} />
        </group>
        <group position={[-3.69, 5.74, -0.47]} rotation={[0.1, -0.08, -1.51]} scale={[1.09, 1.09, 1.09]}>
          <mesh geometry={nodes.cattail_plant025_0.geometry} material={nodes.cattail_plant025_0.material} />
        </group>
        <group position={[-3.29, 6.14, -0.59]} rotation={[-0.07, 0.09, -0.06]} scale={[1.17, 1.17, 1.17]}>
          <mesh geometry={nodes.cattail_plant026_0.geometry} material={nodes.cattail_plant026_0.material} />
        </group>
        <group position={[-3.71, 6.13, -0.55]} rotation={[0.05, 0.14, -2.44]} scale={[1.13, 1.13, 1.13]}>
          <mesh geometry={nodes.cattail_plant027_0.geometry} material={nodes.cattail_plant027_0.material} />
        </group>
        <group position={[-3.01, 5.66, -0.49]} rotation={[0.1, -0.09, -1.5]} scale={[1.18, 1.18, 1.18]}>
          <mesh geometry={nodes.cattail_plant028_0.geometry} material={nodes.cattail_plant028_0.material} />
        </group>
        <group position={[-2.87, 6.01, -0.63]} rotation={[-0.01, 0.03, 1.51]} scale={[1.05, 1.05, 1.05]}>
          <mesh geometry={nodes.cattail_plant029_0.geometry} material={nodes.cattail_plant029_0.material} />
        </group>
        <group position={[-3.11, 5.87, -0.57]} rotation={[-0.06, -0.01, -0.5]} scale={[1, 1, 1.88]}>
          <mesh geometry={nodes.grass_2023_0.geometry} material={nodes.grass_2023_0.material} />
        </group>
        <group position={[-0.57, 8.42, -0.82]} rotation={[-0.01, -0.03, 2.18]} scale={[1.05, 1.05, 1.05]}>
          <mesh geometry={nodes.cattail_plant030_0.geometry} material={nodes.cattail_plant030_0.material} />
        </group>
        <group position={[-0.46, 8.05, -0.68]} rotation={[0.05, 0.13, -0.89]} scale={[1.18, 1.18, 1.18]}>
          <mesh geometry={nodes.cattail_plant031_0.geometry} material={nodes.cattail_plant031_0.material} />
        </group>
        <group position={[-1.3, 7.99, -0.77]} rotation={[-0.03, 0.09, -1.76]} scale={[1.13, 1.13, 1.13]}>
          <mesh geometry={nodes.cattail_plant032_0.geometry} material={nodes.cattail_plant032_0.material} />
        </group>
        <group position={[-0.98, 8.26, -0.8]} rotation={[-0.05, -0.14, 0.61]} scale={[1.17, 1.17, 1.17]}>
          <mesh geometry={nodes.cattail_plant033_0.geometry} material={nodes.cattail_plant033_0.material} />
        </group>
        <group position={[-1.05, 7.7, -0.69]} rotation={[0.09, 0.01, -0.86]} scale={[1.09, 1.09, 1.09]}>
          <mesh geometry={nodes.cattail_plant034_0.geometry} material={nodes.cattail_plant034_0.material} />
        </group>
        <group position={[-1.4, 7.62, -0.71]} rotation={[0.09, 0.01, -0.86]} scale={[0.97, 0.97, 0.97]}>
          <mesh geometry={nodes.cattail_plant035_0.geometry} material={nodes.cattail_plant035_0.material} />
        </group>
        <group position={[-1.75, 7.82, -0.8]} rotation={[-0.11, -0.08, 2.09]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant036_0.geometry} material={nodes.cattail_plant036_0.material} />
        </group>
        <group position={[-1.35, 6.99, -0.62]} rotation={[-0.03, -0.09, 0.73]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant037_0.geometry} material={nodes.cattail_plant037_0.material} />
        </group>
        <group position={[-1.26, 6.87, -0.64]} rotation={[0.08, -0.01, -0.67]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant038_0.geometry} material={nodes.cattail_plant038_0.material} />
        </group>
        <group position={[-0.9, 10.1, -0.69]} rotation={[0, -0.06, -2.05]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant039_0.geometry} material={nodes.cattail_plant039_0.material} />
        </group>
        <group position={[-0.81, 10.21, -0.68]} rotation={[-0.1, 0.03, -0.64]} scale={[0.87, 0.87, 0.87]}>
          <mesh geometry={nodes.cattail_plant040_0.geometry} material={nodes.cattail_plant040_0.material} />
        </group>
        <group position={[-0.3, 10.18, -0.62]} rotation={[-0.17, -0.06, 2.12]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant041_0.geometry} material={nodes.cattail_plant041_0.material} />
        </group>
        <group position={[0.06, 9.99, -0.53]} rotation={[0.03, 0.03, -0.84]} scale={[0.97, 0.97, 0.97]}>
          <mesh geometry={nodes.cattail_plant042_0.geometry} material={nodes.cattail_plant042_0.material} />
        </group>
        <group position={[0.39, 10.06, -0.45]} rotation={[0.03, 0.11, -0.78]} scale={[1.09, 1.09, 1.09]}>
          <mesh geometry={nodes.cattail_plant043_0.geometry} material={nodes.cattail_plant043_0.material} />
        </group>
        <group position={[0.47, 10.63, -0.54]} rotation={[-0.04, -0.26, 0.65]} scale={[1.17, 1.17, 1.17]}>
          <mesh geometry={nodes.cattail_plant044_0.geometry} material={nodes.cattail_plant044_0.material} />
        </group>
        <group position={[0.15, 10.36, -0.56]} rotation={[0.01, -0.01, -1.76]} scale={[1.13, 1.13, 1.13]}>
          <mesh geometry={nodes.cattail_plant045_0.geometry} material={nodes.cattail_plant045_0.material} />
        </group>
        <group position={[0.98, 10.42, -0.37]} rotation={[0.08, 0.03, -0.89]} scale={[1.18, 1.18, 1.18]}>
          <mesh geometry={nodes.cattail_plant046_0.geometry} material={nodes.cattail_plant046_0.material} />
        </group>
        <group position={[0.89, 10.79, -0.51]} rotation={[0.05, -0.08, 2.15]} scale={[1.05, 1.05, 1.05]}>
          <mesh geometry={nodes.cattail_plant047_0.geometry} material={nodes.cattail_plant047_0.material} />
        </group>
        <group position={[0.5, 10.22, -0.58]} rotation={[0.02, -0.13, 1.78]} scale={[1.54, 1.54, 2.76]}>
          <mesh geometry={nodes.grass_2024_0.geometry} material={nodes.grass_2024_0.material} />
        </group>
        <group position={[-0.52, 10.29, -0.81]} rotation={[0.07, -0.09, 0.45]} scale={[1.54, 1.54, 2.43]}>
          <mesh geometry={nodes.grass_2025_0.geometry} material={nodes.grass_2025_0.material} />
        </group>
        <group position={[-1.22, 8.28, -0.81]} rotation={[0.07, -0.09, 0.45]} scale={[1.54, 1.54, 2.43]}>
          <mesh geometry={nodes.grass_2026_0.geometry} material={nodes.grass_2026_0.material} />
        </group>
        <group position={[-4.57, 6.42, -0.52]} rotation={[-0.1, 0.15, 1.11]} scale={[1.05, 1.04, 2.03]}>
          <mesh geometry={nodes.grass_2027_0.geometry} material={nodes.grass_2027_0.material} />
        </group>
        <group position={[-6.64, 4.16, -0.65]} rotation={[-0.09, -0.01, 1.9]} scale={[1.05, 1.04, 2.03]}>
          <mesh geometry={nodes.grass_2028_0.geometry} material={nodes.grass_2028_0.material} />
        </group>
        <group position={[-7.12, -2.57, -0.66]} rotation={[-0.07, -0.06, -0.9]} scale={[1.14, 1.14, 1.49]}>
          <mesh geometry={nodes.grass_2029_0.geometry} material={nodes.grass_2029_0.material} />
        </group>
        <group position={[-7.32, -0.6, -0.95]} rotation={[-0.1, -0.07, 1.2]} scale={[0.95, 0.95, 0.95]}>
          <mesh geometry={nodes.cattail_plant048_0.geometry} material={nodes.cattail_plant048_0.material} />
        </group>
        <group position={[-7.6, -1.66, -0.74]} rotation={[0.06, -0.15, -2.39]} scale={[0.81, 0.81, 0.81]}>
          <mesh geometry={nodes.cattail_plant049_0.geometry} material={nodes.cattail_plant049_0.material} />
        </group>
        <group position={[-7.33, -1.64, -0.72]} rotation={[-0.07, -0.26, 0.54]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.cattail_plant050_0.geometry} material={nodes.cattail_plant050_0.material} />
        </group>
        <group position={[-7.59, -1.37, -0.76]} rotation={[-0.15, -0.26, -0.17]} scale={[0.92, 0.92, 0.92]}>
          <mesh geometry={nodes.cattail_plant051_0.geometry} material={nodes.cattail_plant051_0.material} />
        </group>
        <group position={[-7.15, -1.11, -0.61]} rotation={[0.08, -0.2, -0.07]} scale={[0.86, 0.86, 0.86]}>
          <mesh geometry={nodes.cattail_plant052_0.geometry} material={nodes.cattail_plant052_0.material} />
        </group>
        <group position={[-7.2, -0.87, -0.78]} rotation={[-0.06, -0.05, 0.68]} scale={[1.07, 1.07, 1.07]}>
          <mesh geometry={nodes.cattail_plant053_0.geometry} material={nodes.cattail_plant053_0.material} />
        </group>
        <group position={[-7.75, -0.74, -0.86]} rotation={[-0.01, -0.06, -0.09]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant054_0.geometry} material={nodes.cattail_plant054_0.material} />
        </group>
        <group position={[-9.84, -4.3, -0.38]} rotation={[-0.25, -0.09, -1.72]} scale={[1.14, 1.14, 1.49]}>
          <mesh geometry={nodes.grass_2030_0.geometry} material={nodes.grass_2030_0.material} />
        </group>
        <group position={[-7.37, -1.96, -0.83]} rotation={[0.1, 0.05, 0.8]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.cattail_plant055_0.geometry} material={nodes.cattail_plant055_0.material} />
        </group>
        <group position={[-7.11, -2.42, -0.65]} rotation={[0.09, 0.19, 3.13]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.cattail_plant056_0.geometry} material={nodes.cattail_plant056_0.material} />
        </group>
        <group position={[-7.41, -2.82, -0.85]} rotation={[0.23, -0.06, 0.42]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.cattail_plant057_0.geometry} material={nodes.cattail_plant057_0.material} />
        </group>
        <group position={[-7.81, -2.4, -0.8]} rotation={[0.07, 0, 0.51]} scale={[0.98, 0.98, 0.98]}>
          <mesh geometry={nodes.cattail_plant058_0.geometry} material={nodes.cattail_plant058_0.material} />
        </group>
        <group position={[-7.9, -3.38, -0.66]} rotation={[-0.04, -0.09, 0.51]} scale={[0.97, 0.97, 0.97]}>
          <mesh geometry={nodes.cattail_plant059_0.geometry} material={nodes.cattail_plant059_0.material} />
        </group>
        <group position={[-7.67, -2.79, -0.66]} rotation={[0.09, 0.07, 0.53]} scale={[0.71, 0.71, 0.71]}>
          <mesh geometry={nodes.cattail_plant060_0.geometry} material={nodes.cattail_plant060_0.material} />
        </group>
        <group position={[-7.36, -3.1, -0.71]} rotation={[0.28, 0.02, 0.44]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.cattail_plant061_0.geometry} material={nodes.cattail_plant061_0.material} />
        </group>
        <group position={[-0.29, -10.82, 2.87]} rotation={[-0.12, -0.26, -0.56]} scale={[1.93, 1.95, 1.45]}>
          <mesh geometry={nodes.grass_2031_0.geometry} material={nodes.grass_2031_0.material} />
        </group>
        <group position={[-5.18, -7.87, 1.54]} rotation={[-0.14, -0.28, -0.57]} scale={[1.93, 1.95, 1.45]}>
          <mesh geometry={nodes.grass_2032_0.geometry} material={nodes.grass_2032_0.material} />
        </group>
        <group position={[-3.98, -3.93, -0.02]} rotation={[-0.27, 0.03, -2.47]} scale={[1.31, 1.32, 0.98]}>
          <mesh geometry={nodes.grass_2033_0.geometry} material={nodes.grass_2033_0.material} />
        </group>
        <group position={[-2.31, -6.85, 3.32]} rotation={[0.79, -0.13, -0.09]} scale={[0.06, 0.4, 0.39]}>
          <mesh geometry={nodes.Cube000_0.geometry} material={nodes.Cube000_0.material} />
        </group>
        <group position={[-2.28, -6.43, 3.69]} rotation={[0, 0.01, -0.13]} scale={[0.13, 0.69, 0.64]}>
          <mesh geometry={nodes.Cube001_0.geometry} material={nodes.Cube001_0.material} />
        </group>
        <group position={[-5.73, 6.01, 1.78]} scale={[22.68, 22.68, 3.23]}>
          <mesh geometry={nodes.fog_background_0.geometry} material={nodes.fog_background_0.material} />
        </group>
        <group position={[-2.59, 5.06, 0.05]} rotation={[-1.28, -0.4, 0.09]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fish_0.geometry} material={nodes.fish_0.material} />
        </group>
        <group position={[2.99, 13.3, -0.58]} rotation={[0.06, -0.18, 1.14]} scale={[1.75, 1.75, 1.75]}>
          <mesh geometry={nodes.Cylinder015_0.geometry} material={nodes.Cylinder015_0.material} />
        </group>
        <group position={[0.25, 11.29, -0.36]} rotation={[-0.09, -0.18, 0.94]} scale={[1.08, 1.08, 1.37]}>
          <mesh geometry={nodes.grass_2034_0.geometry} material={nodes.grass_2034_0.material} />
        </group>
        <group position={[1.49, 10.57, -0.16]} rotation={[-0.01, -0.21, -1.01]} scale={[2.03, 2.03, 1.55]}>
          <mesh geometry={nodes.grass_1010_0.geometry} material={nodes.grass_1010_0.material} />
        </group>
        <group position={[7.13, 10.87, -0.8]} rotation={[-0.09, 0.16, 0.9]} scale={[2.09, 2.09, 1.28]}>
          <mesh geometry={nodes.Hillhock009_0.geometry} material={nodes.Hillhock009_0.material} />
        </group>
        <group position={[-3.62, 3.05, -0.37]} rotation={[0.06, -0.01, 0.5]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.scarecrow001_0.geometry} material={materials.scarecrow_material} />
        </group>
        <group position={[-3.62, 3.05, -0.37]} rotation={[0.06, -0.01, 0.5]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.scarecrow_target_0.geometry} material={materials.scarecrow_target} />
        </group>
        <group position={[-10.39, -5.46, -0.25]} rotation={[-0.33, -0.26, -2.29]} scale={[1.24, 1.24, 1.62]}>
          <mesh geometry={nodes.grass_2035_0.geometry} material={nodes.grass_2035_0.material} />
        </group>
        <group position={[-5.86, -0.16, -0.22]} rotation={[-0.01, -0.01, 0.96]} scale={[0.97, 0.97, 0.97]}>
          <mesh geometry={nodes.rock_2009_0.geometry} material={nodes.rock_2009_0.material} />
        </group>
        <group position={[-5.95, 0.24, -0.26]} rotation={[-0.01, -0.51, -1.34]} scale={[0.64, 0.64, 0.64]}>
          <mesh geometry={nodes.rock_2010_0.geometry} material={nodes.rock_2010_0.material} />
        </group>
        <group position={[-5.43, 5.78, -0.5]} rotation={[0.07, -0.1, 2.98]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.cattail_plant021_0.geometry} material={nodes.cattail_plant021_0.material} />
        </group>
        <group position={[-5.91, -1.12, -0.16]} rotation={[-0.04, -0.06, 2.6]} scale={[1.5, 1.5, 1.23]}>
          <mesh geometry={nodes.grass_1011_0.geometry} material={nodes.grass_1011_0.material} />
        </group>
        <group position={[-5.1, 2.46, -0.25]} rotation={[-0.1, -0.33, -1.33]} scale={[1.14, 1.14, 1.14]}>
          <mesh geometry={nodes.rock_2011_0.geometry} material={nodes.rock_2011_0.material} />
        </group>
        <group position={[-0.44, 5.1, 0.02]} rotation={[0, -0.03, -0.99]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.leafs_0.geometry} material={nodes.leafs_0.material} />
        </group>
        <group position={[1.72, -1.83, 0.36]} rotation={[-0.03, -0.08, 0]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.Plane018_0.geometry} material={nodes.Plane018_0.material} />
        </group>
        <group position={[4.12, 0.36, 0.3]} rotation={[-0.04, -0.01, -0.97]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.Plane019_0.geometry} material={nodes.Plane019_0.material} />
        </group>
        <group position={[-2.76, 3.23, -0.03]} rotation={[-0.02, -0.06, 0.32]} scale={[0.83, 0.83, 0.83]}>
          <mesh geometry={nodes.Plane020_0.geometry} material={nodes.Plane020_0.material} />
        </group>
        <group position={[0.88, -4.01, 0.49]} rotation={[-0.1, 0, 0.22]} scale={[0.83, 0.83, 0.83]}>
          <mesh geometry={nodes.Plane021_0.geometry} material={nodes.Plane021_0.material} />
        </group>
        <group position={[-3.43, -4.69, 0.27]} rotation={[-0.12, -0.16, 0.24]} scale={[0.83, 0.83, 0.83]}>
          <mesh geometry={nodes.Plane022_0.geometry} material={nodes.Plane022_0.material} />
        </group>
        <group position={[-4.25, -0.75, 0]} rotation={[-0.04, -0.03, -0.34]} scale={[0.83, 0.83, 0.83]}>
          <mesh geometry={nodes.Plane023_0.geometry} material={nodes.Plane023_0.material} />
        </group>
        <group position={[0.62, -7.96, 0.87]} rotation={[-0.11, -0.17, -0.51]} scale={[0.83, 0.83, 0.83]}>
          <mesh geometry={nodes.Plane024_0.geometry} material={nodes.Plane024_0.material} />
        </group>
        <group position={[-1.96, 1.21, -0.05]} rotation={[-0.11, 0.19, 1.53]} scale={[0.8, 0.8, 0.8]}>
          <mesh geometry={nodes.rock_2012_0.geometry} material={nodes.rock_2012_0.material} />
        </group>
        <group position={[-1.84, 0.09, 0.03]} rotation={[-0.13, -0.13, -2.97]} scale={[0.93, 0.93, 0.93]}>
          <mesh geometry={nodes.rock_2013_0.geometry} material={nodes.rock_2013_0.material} />
        </group>
        <group position={[-1.53, 0.01, 0.03]} rotation={[0.06, -0.18, -1.86]} scale={[0.62, 0.62, 0.62]}>
          <mesh geometry={nodes.rock_2014_0.geometry} material={nodes.rock_2014_0.material} />
        </group>
        <group position={[-0.9, 0.92, 0]} rotation={[-0.14, 0.28, 1.56]} scale={[0.8, 0.8, 0.8]}>
          <mesh geometry={nodes.rock_2015_0.geometry} material={nodes.rock_2015_0.material} />
        </group>
        <group position={[-1.06, 1.19, -0.02]} rotation={[0.28, 0.15, 0.02]} scale={[0.64, 0.64, 0.64]}>
          <mesh geometry={nodes.rock_2016_0.geometry} material={nodes.rock_2016_0.material} />
        </group>
        <group position={[4.22, -3.31, 9.85]} rotation={[-0.13, -0.02, 0.24]} scale={[0.24, 0.24, 0.24]}>
          <mesh
            name="smoke_0"
            geometry={nodes.smoke_0.geometry}
            material={nodes.smoke_0.material}
            morphTargetDictionary={nodes.smoke_0.morphTargetDictionary}
            morphTargetInfluences={nodes.smoke_0.morphTargetInfluences}
          />
        </group>
        <group position={[4.9, -1.22, 0.25]} rotation={[-0.53, -0.15, 0.65]} scale={[1.74, 1.74, 1.43]}>
          <mesh geometry={nodes.grass_1012_0.geometry} material={nodes.grass_1012_0.material} />
        </group>
        <group position={[4.67, -1.8, 0.4]} rotation={[-0.24, 0.02, 0.57]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.grass_2036_0.geometry} material={nodes.grass_2036_0.material} />
        </group>
        <group position={[-2.22, 5.61, -0.27]} rotation={[-0.06, 0.18, 0.86]} scale={[0.8, 0.8, 0.8]}>
          <mesh geometry={nodes.rock_2017_0.geometry} material={nodes.rock_2017_0.material} />
        </group>
        <group position={[12.28, -0.6, 2.95]} rotation={[-0.06, 0.01, 0.22]} scale={[1.69, 1.7, 1.25]}>
          <mesh geometry={nodes.tree_2008_0.geometry} material={nodes.tree_2008_0.material} />
        </group>
        <group position={[3.62, -12, 3.11]} rotation={[0.08, -0.24, -0.46]} scale={[2.28, 2.28, 1.76]}>
          <mesh geometry={nodes.tree_2009_0.geometry} material={nodes.tree_2009_0.material} />
        </group>
        <group position={[-7.01, 23.21, 0.68]} rotation={[0.08, -0.05, 2.33]} scale={[3.7, 4.14, 3.86]}>
          <mesh geometry={nodes.bush_1013_0.geometry} material={nodes.bush_1013_0.material} />
        </group>
        <group position={[-22.24, -0.08, 0.25]} rotation={[0.31, 0.21, 0.22]} scale={[1.35, 1.17, 1.07]}>
          <mesh geometry={nodes.tree_2000_0.geometry} material={nodes.tree_2000_0.material} />
        </group>
        <group position={[-18.25, 7.43, -0.03]} rotation={[0.04, -0.13, 2.54]} scale={[1.84, 1.81, 1.59]}>
          <mesh geometry={nodes.tree_2003_0.geometry} material={nodes.tree_2003_0.material} />
        </group>
        <group position={[1.19, 0.29, 0.2]} rotation={[-0.06, -0.06, 1.07]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.Plane025_0.geometry} material={nodes.Plane025_0.material} />
        </group>
        <group position={[2.35, -3, 4.54]} rotation={[0.03, 0.01, 0.64]} scale={[0.9, 0.9, 0.9]}>
          <mesh geometry={nodes.bottle_2004_0.geometry} material={nodes.bottle_2004_0.material} />
        </group>
        <group position={[2.8, -3.18, 4.53]} rotation={[-0.03, 0, 2.72]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.book_1013_0.geometry} material={nodes.book_1013_0.material} />
        </group>
        <group position={[2.88, -3.14, 4.17]} rotation={[2.31, -1.55, 0.79]} scale={[0.88, 0.88, 0.88]}>
          <mesh geometry={nodes.book_1014_0.geometry} material={nodes.book_1014_0.material} />
        </group>
        <group position={[3.06, -2.82, 3.97]} rotation={[0.01, -0.05, -1.49]} scale={[0.75, 0.75, 1.4]}>
          <mesh geometry={nodes.book_1015_0.geometry} material={nodes.book_1015_0.material} />
        </group>
        <group position={[4.44, -1.03, 4.64]} rotation={[-0.05, -0.07, -0.9]} scale={[0.81, 0.81, 0.81]}>
          <mesh geometry={nodes.book_1003_0.geometry} material={nodes.book_1003_0.material} />
        </group>
        <group position={[1.29, -5.12, 0.53]} rotation={[-0.18, 0.11, -0.55]} scale={[1.86, 1.86, 1.86]}>
          <mesh geometry={nodes.mushroom_2002_0.geometry} material={nodes.mushroom_2002_0.material} />
        </group>
        <group position={[1.1, -5.24, 0.53]} rotation={[0.01, -0.08, -0.02]} scale={[1.31, 1.31, 1.31]}>
          <mesh geometry={nodes.mushroom_2003_0.geometry} material={nodes.mushroom_2003_0.material} />
        </group>
        <group position={[6.14, 1.85, 1.31]} rotation={[0.14, -0.01, 0.31]} scale={[1.28, 1.28, 1.28]}>
          <mesh geometry={nodes.grass_2037_0.geometry} material={nodes.grass_2037_0.material} />
        </group>
        <group position={[6.31, -2.14, 0.41]} rotation={[-0.35, 0.05, -2.38]} scale={[1.21, 1.23, 1.54]}>
          <mesh geometry={nodes.grass_2038_0.geometry} material={nodes.grass_2038_0.material} />
        </group>
        <group position={[5.82, 1.98, 1.33]} rotation={[-0.23, -0.12, -2.07]} scale={[1.7, 1.7, 1.86]}>
          <mesh geometry={nodes.mushroom_1004_0.geometry} material={nodes.mushroom_1004_0.material} />
        </group>
        <group position={[-8.81, -6.61, -0.24]} rotation={[-0.17, -0.39, -1.78]} scale={[1.68, 1.68, 2.19]}>
          <mesh geometry={nodes.grass_2039_0.geometry} material={nodes.grass_2039_0.material} />
        </group>
        <group position={[2.19, -2.51, 0.26]} rotation={[-0.05, -0.08, 0.48]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.grass_2040_0.geometry} material={nodes.grass_2040_0.material} />
        </group>
        <group position={[0.73, 4.4, -0.05]} rotation={[0.13, 0.21, 0.44]} scale={[1.23, 1.23, 1.23]}>
          <mesh geometry={nodes.rock_2018_0.geometry} material={nodes.rock_2018_0.material} />
        </group>
        <group position={[0.97, 4.2, 0.05]} rotation={[-0.1, -0.33, -1.33]} scale={[0.92, 0.92, 0.92]}>
          <mesh geometry={nodes.rock_2019_0.geometry} material={nodes.rock_2019_0.material} />
        </group>
        <group position={[1.18, 4.49, -0.05]} rotation={[0.02, -0.52, 2.84]} scale={[1.62, 1.62, 1.05]}>
          <mesh geometry={nodes.rock_2020_0.geometry} material={nodes.rock_2020_0.material} />
        </group>
        <group position={[0.86, 4.71, -0.1]} rotation={[0.06, -0.04, 1.45]} scale={[0.83, 0.82, 0.85]}>
          <mesh geometry={nodes.grass_1013_0.geometry} material={nodes.grass_1013_0.material} />
        </group>
        <group position={[0.36, 6.99, -0.23]} rotation={[0.14, 0.18, 0.92]} scale={[1.4, 1.4, 1.4]}>
          <mesh geometry={nodes.mushroom_2004_0.geometry} material={nodes.mushroom_2004_0.material} />
        </group>
        <group position={[0.3, 7.29, -0.27]} rotation={[-0.04, -0.14, -0.61]} scale={[1.24, 1.24, 1.36]}>
          <mesh geometry={nodes.mushroom_1005_0.geometry} material={nodes.mushroom_1005_0.material} />
        </group>
        <group position={[1.23, 7.33, -0.27]} rotation={[-0.07, -0.28, -0.57]} scale={[1.48, 1.48, 1.62]}>
          <mesh geometry={nodes.mushroom_1006_0.geometry} material={nodes.mushroom_1006_0.material} />
        </group>
        <group position={[-2.64, 5.2, -0.08]} rotation={[-1.04, -0.76, -2.49]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.fish001_0.geometry} material={nodes.fish001_0.material} />
        </group>
        <group position={[2.05, -1.7, 6.31]} scale={1.63}>
          <mesh geometry={nodes.Plane004_0.geometry} material={nodes.Plane004_0.material} />
        </group>
        <group position={[-3.32, 23.24, 2.04]} rotation={[-0.06, 0.03, -1.23]} scale={[1.93, 1.9, 1.48]}>
          <mesh geometry={nodes.tree_2005_0.geometry} material={nodes.tree_2005_0.material} />
        </group>
        <group position={[-9.46, -9.22, -0.16]} rotation={[0.06, 0.04, -2.45]} scale={[1.24, 1.24, 1.24]}>
          <mesh geometry={nodes.Hillhock011_0.geometry} material={nodes.Hillhock011_0.material} />
        </group>
        <group position={[-3.62, 3.05, -0.37]} rotation={[0.06, -0.01, 0.5]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.scarecrow_circles_0.geometry} material={nodes.scarecrow_circles_0.material} />
        </group>
        <group position={[4.01, -0.57, 4.67]} rotation={[-0.1, -0.02, 0.47]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.hut_door001_0.geometry} material={nodes.hut_door001_0.material} />
        </group>
        <group position={[-3.49, -6.24, 1.51]} scale={[0.56, 0.56, 0.93]}>
          <mesh
            name="fire_0"
            geometry={nodes.fire_0.geometry}
            material={nodes.fire_0.material}
            morphTargetDictionary={nodes.fire_0.morphTargetDictionary}
            morphTargetInfluences={nodes.fire_0.morphTargetInfluences}
          />
        </group>
        <group position={[-0.59, -1.48, 0.54]} rotation={[0.02, 0.11, -2.35]} scale={[1, 1, 1]}>
          <primitive object={nodes.Armature_Baba_Yaga_rootJoint} />
          <skinnedMesh
            geometry={nodes.Baba_Yaga_0.geometry}
            material={materials.Baba_yaga_mat}
            skeleton={nodes.Baba_Yaga_0.skeleton}
          />
        </group>
        <group position={[2.53, 4.17, -0.07]} rotation={[0.14, 0.1, 1.55]} scale={[1.5, 1.5, 1.15]}>
          <mesh geometry={nodes.grass_1014_0.geometry} material={nodes.grass_1014_0.material} />
        </group>
        <group position={[-1.73, 5.61, 0.37]} rotation={[0, 0, -2.73]} scale={[1, 1, 1]}>
          <primitive object={nodes.Armature_imp001_rootJoint} />
          <skinnedMesh
            geometry={nodes.Imp001_0.geometry}
            material={nodes.Imp001_0.material}
            skeleton={nodes.Imp001_0.skeleton}
          />
        </group>
        <group position={[-1.09, 0.87, -0.13]} rotation={[0, 0, -0.4]} scale={[5.94, 5.94, 7.22]}>
          <mesh geometry={nodes.Vr_cage_0.geometry} material={materials.Transparent} />
        </group>
        <group position={[2.23, -1.66, 3.93]} scale={1.32}>
          <mesh geometry={nodes.bottle_1008_0.geometry} material={nodes.bottle_1008_0.material} />
        </group>
        <group position={[2.12, -1.38, 3.94]} scale={1.46}>
          <mesh geometry={nodes.bottle_1009_0.geometry} material={nodes.bottle_1009_0.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
